<?php

namespace Database\Seeders;

use App\Models\DonHang;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DonHangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('don_hangs')->delete();
        DB::table('don_hangs')->truncate();
        DB::table('don_hangs')->insert([
            [
                'id' => 1,
                'ma_don_hang' => 'DH001',
                'id_khach_hang' => 1,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 2,
                'id_dia_chi_nhan' => 1,
                'ten_nguoi_nhan' => 'Võ Văn Việt',
                'so_dien_thoai' => '0123456780',
                'tien_hang' => 35000,
                'phi_ship' => 10000,
                'tong_tien' => 45000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-02-19 10:34:00',
                'updated_at' => '2025-02-19 10:34:00',
            ],
            [
                'id' => 2,
                'ma_don_hang' => 'DH002',
                'id_khach_hang' => 2,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 3,
                'id_dia_chi_nhan' => 2,
                'ten_nguoi_nhan' => 'Nguyễn Văn A',
                'so_dien_thoai' => '0123456789',
                'tien_hang' => 25000,
                'phi_ship' => 8000,
                'tong_tien' => 33000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-02-20 14:00:00',
                'updated_at' => '2025-02-20 14:00:00',
            ],
            [
                'id' => 3,
                'ma_don_hang' => 'DH003',
                'id_khach_hang' => 3,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 4,
                'id_dia_chi_nhan' => 3,
                'ten_nguoi_nhan' => 'Lê Minh Tuấn',
                'so_dien_thoai' => '0987654321',
                'tien_hang' => 55000,
                'phi_ship' => 12000,
                'tong_tien' => 67000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-02-22 11:45:00',
                'updated_at' => '2025-02-22 11:45:00',
            ],
            [
                'id' => 4,
                'ma_don_hang' => 'DH004',
                'id_khach_hang' => 4,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 5,
                'id_dia_chi_nhan' => 4,
                'ten_nguoi_nhan' => 'Trần Thị Hồng Nhung',
                'so_dien_thoai' => '0911223344',
                'tien_hang' => 30000,
                'phi_ship' => 10000,
                'tong_tien' => 40000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-01 13:22:00',
                'updated_at' => '2025-03-01 13:22:00',
            ],
            [
                'id' => 5,
                'ma_don_hang' => 'DH005',
                'id_khach_hang' => 5,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 6,
                'id_dia_chi_nhan' => 5,
                'ten_nguoi_nhan' => 'Đặng Quốc Huy',
                'so_dien_thoai' => '0933445566',
                'tien_hang' => 45000,
                'phi_ship' => 12000,
                'tong_tien' => 57000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-05 15:30:00',
                'updated_at' => '2025-03-05 15:30:00',
            ],
            [
                'id' => 6,
                'ma_don_hang' => 'DH006',
                'id_khach_hang' => 6,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 7,
                'id_dia_chi_nhan' => 6,
                'ten_nguoi_nhan' => 'Phạm Thị Mai',
                'so_dien_thoai' => '0909887766',
                'tien_hang' => 50000,
                'phi_ship' => 10000,
                'tong_tien' => 60000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-10 10:15:00',
                'updated_at' => '2025-03-10 10:15:00',
            ],
            [
                'id' => 7,
                'ma_don_hang' => 'DH007',
                'id_khach_hang' => 7,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 8,
                'id_dia_chi_nhan' => 7,
                'ten_nguoi_nhan' => 'Ngô Văn Lâm',
                'so_dien_thoai' => '0966887799',
                'tien_hang' => 25000,
                'phi_ship' => 12000,
                'tong_tien' => 37000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-15 11:45:00',
                'updated_at' => '2025-03-15 11:45:00',
            ],
            [
                'id' => 8,
                'ma_don_hang' => 'DH008',
                'id_khach_hang' => 1,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 9,
                'id_dia_chi_nhan' => 8,
                'ten_nguoi_nhan' => 'Võ Văn Việt',
                'so_dien_thoai' => '0123456780',
                'tien_hang' => 40000,
                'phi_ship' => 10000,
                'tong_tien' => 50000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-20 16:00:00',
                'updated_at' => '2025-03-20 16:00:00',
            ],
            [
                'id' => 9,
                'ma_don_hang' => 'DH009',
                'id_khach_hang' => 2,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 10,
                'id_dia_chi_nhan' => 9,
                'ten_nguoi_nhan' => 'Nguyễn Văn A',
                'so_dien_thoai' => '0123456789',
                'tien_hang' => 30000,
                'phi_ship' => 10000,
                'tong_tien' => 40000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-25 09:30:00',
                'updated_at' => '2025-03-25 09:30:00',
            ],
            [
                'id' => 10,
                'ma_don_hang' => 'DH010',
                'id_khach_hang' => 3,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 11,
                'id_dia_chi_nhan' => 10,
                'ten_nguoi_nhan' => 'Lê Minh Tuấn',
                'so_dien_thoai' => '0987654321',
                'tien_hang' => 45000,
                'phi_ship' => 12000,
                'tong_tien' => 57000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-01 14:15:00',
                'updated_at' => '2025-04-01 14:15:00',
            ],
            [
                'id' => 11,
                'ma_don_hang' => 'DH011',
                'id_khach_hang' => 4,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 10,
                'id_dia_chi_nhan' => 4,
                'ten_nguoi_nhan' => 'Trần Thị Hồng Nhung',
                'so_dien_thoai' => '0911223344',
                'tien_hang' => 30000,
                'phi_ship' => 12000,
                'tong_tien' => 42000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-18 11:00:00',
                'updated_at' => '2025-03-18 11:00:00',
            ],
            [
                'id' => 12,
                'ma_don_hang' => 'DH012',
                'id_khach_hang' => 5,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 11,
                'id_dia_chi_nhan' => 5,
                'ten_nguoi_nhan' => 'Đặng Quốc Huy',
                'so_dien_thoai' => '0933445566',
                'tien_hang' => 50000,
                'phi_ship' => 10000,
                'tong_tien' => 60000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-22 09:30:00',
                'updated_at' => '2025-03-22 09:30:00',
            ],
            [
                'id' => 13,
                'ma_don_hang' => 'DH013',
                'id_khach_hang' => 6,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 12,
                'id_dia_chi_nhan' => 6,
                'ten_nguoi_nhan' => 'Phạm Thị Mai',
                'so_dien_thoai' => '0909887766',
                'tien_hang' => 45000,
                'phi_ship' => 12000,
                'tong_tien' => 57000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-24 10:45:00',
                'updated_at' => '2025-03-24 10:45:00',
            ],
            [
                'id' => 14,
                'ma_don_hang' => 'DH014',
                'id_khach_hang' => 7,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 13,
                'id_dia_chi_nhan' => 7,
                'ten_nguoi_nhan' => 'Ngô Văn Lâm',
                'so_dien_thoai' => '0966887799',
                'tien_hang' => 25000,
                'phi_ship' => 8000,
                'tong_tien' => 33000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-26 12:00:00',
                'updated_at' => '2025-03-26 12:00:00',
            ],
            [
                'id' => 15,
                'ma_don_hang' => 'DH015',
                'id_khach_hang' => 1,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 14,
                'id_dia_chi_nhan' => 8,
                'ten_nguoi_nhan' => 'Võ Văn Việt',
                'so_dien_thoai' => '0123456780',
                'tien_hang' => 30000,
                'phi_ship' => 12000,
                'tong_tien' => 42000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-28 14:30:00',
                'updated_at' => '2025-03-28 14:30:00',
            ],
            [
                'id' => 16,
                'ma_don_hang' => 'DH016',
                'id_khach_hang' => 2,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 15,
                'id_dia_chi_nhan' => 9,
                'ten_nguoi_nhan' => 'Nguyễn Văn A',
                'so_dien_thoai' => '0123456789',
                'tien_hang' => 40000,
                'phi_ship' => 10000,
                'tong_tien' => 50000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-30 16:15:00',
                'updated_at' => '2025-03-30 16:15:00',
            ],
            [
                'id' => 17,
                'ma_don_hang' => 'DH017',
                'id_khach_hang' => 3,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 16,
                'id_dia_chi_nhan' => 10,
                'ten_nguoi_nhan' => 'Lê Minh Tuấn',
                'so_dien_thoai' => '0987654321',
                'tien_hang' => 50000,
                'phi_ship' => 8000,
                'tong_tien' => 58000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-02 10:00:00',
                'updated_at' => '2025-04-02 10:00:00',
            ],
            [
                'id' => 18,
                'ma_don_hang' => 'DH018',
                'id_khach_hang' => 4,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 17,
                'id_dia_chi_nhan' => 1,
                'ten_nguoi_nhan' => 'Trần Thị Hồng Nhung',
                'so_dien_thoai' => '0911223344',
                'tien_hang' => 35000,
                'phi_ship' => 12000,
                'tong_tien' => 47000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-05 11:30:00',
                'updated_at' => '2025-04-05 11:30:00',
            ],
            [
                'id' => 19,
                'ma_don_hang' => 'DH019',
                'id_khach_hang' => 5,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 18,
                'id_dia_chi_nhan' => 2,
                'ten_nguoi_nhan' => 'Đặng Quốc Huy',
                'so_dien_thoai' => '0933445566',
                'tien_hang' => 25000,
                'phi_ship' => 10000,
                'tong_tien' => 35000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-07 14:45:00',
                'updated_at' => '2025-04-07 14:45:00',
            ],
            [
                'id' => 20,
                'ma_don_hang' => 'DH020',
                'id_khach_hang' => 6,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 19,
                'id_dia_chi_nhan' => 3,
                'ten_nguoi_nhan' => 'Phạm Thị Mai',
                'so_dien_thoai' => '0909887766',
                'tien_hang' => 40000,
                'phi_ship' => 12000,
                'tong_tien' => 52000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-10 16:00:00',
                'updated_at' => '2025-04-10 16:00:00',
            ],
            [
                'id' => 21,
                'ma_don_hang' => 'DH021',
                'id_khach_hang' => 1,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 3,
                'id_dia_chi_nhan' => 21,
                'ten_nguoi_nhan' => 'Võ Văn Việt',
                'so_dien_thoai' => '0123456780',
                'tien_hang' => 60000,
                'phi_ship' => 10000,
                'tong_tien' => 70000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-18 11:00:00',
                'updated_at' => '2025-03-18 11:00:00',
            ],
            [
                'id' => 22,
                'ma_don_hang' => 'DH022',
                'id_khach_hang' => 2,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 4,
                'id_dia_chi_nhan' => 22,
                'ten_nguoi_nhan' => 'Nguyễn Văn A',
                'so_dien_thoai' => '0123456789',
                'tien_hang' => 75000,
                'phi_ship' => 12000,
                'tong_tien' => 87000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-20 14:30:00',
                'updated_at' => '2025-03-20 14:30:00',
            ],
            [
                'id' => 23,
                'ma_don_hang' => 'DH023',
                'id_khach_hang' => 3,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 5,
                'id_dia_chi_nhan' => 23,
                'ten_nguoi_nhan' => 'Lê Minh Tuấn',
                'so_dien_thoai' => '0987654321',
                'tien_hang' => 50000,
                'phi_ship' => 8000,
                'tong_tien' => 58000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-22 15:45:00',
                'updated_at' => '2025-03-22 15:45:00',
            ],
            [
                'id' => 24,
                'ma_don_hang' => 'DH024',
                'id_khach_hang' => 4,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 6,
                'id_dia_chi_nhan' => 24,
                'ten_nguoi_nhan' => 'Trần Thị Hồng Nhung',
                'so_dien_thoai' => '0911223344',
                'tien_hang' => 85000,
                'phi_ship' => 10000,
                'tong_tien' => 95000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-25 09:00:00',
                'updated_at' => '2025-03-25 09:00:00',
            ],
            [
                'id' => 25,
                'ma_don_hang' => 'DH025',
                'id_khach_hang' => 5,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 7,
                'id_dia_chi_nhan' => 25,
                'ten_nguoi_nhan' => 'Đặng Quốc Huy',
                'so_dien_thoai' => '0933445566',
                'tien_hang' => 65000,
                'phi_ship' => 12000,
                'tong_tien' => 77000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-27 11:20:00',
                'updated_at' => '2025-03-27 11:20:00',
            ],
            [
                'id' => 26,
                'ma_don_hang' => 'DH026',
                'id_khach_hang' => 6,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 8,
                'id_dia_chi_nhan' => 26,
                'ten_nguoi_nhan' => 'Phạm Thị Mai',
                'so_dien_thoai' => '0909887766',
                'tien_hang' => 70000,
                'phi_ship' => 10000,
                'tong_tien' => 80000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-29 16:45:00',
                'updated_at' => '2025-03-29 16:45:00',
            ],
            [
                'id' => 27,
                'ma_don_hang' => 'DH027',
                'id_khach_hang' => 7,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 9,
                'id_dia_chi_nhan' => 27,
                'ten_nguoi_nhan' => 'Ngô Văn Lâm',
                'so_dien_thoai' => '0966887799',
                'tien_hang' => 90000,
                'phi_ship' => 12000,
                'tong_tien' => 102000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-30 14:00:00',
                'updated_at' => '2025-03-30 14:00:00',
            ],
            [
                'id' => 28,
                'ma_don_hang' => 'DH028',
                'id_khach_hang' => 1,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 10,
                'id_dia_chi_nhan' => 8,
                'ten_nguoi_nhan' => 'Võ Văn Việt',
                'so_dien_thoai' => '0123456780',
                'tien_hang' => 55000,
                'phi_ship' => 10000,
                'tong_tien' => 65000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-02 12:15:00',
                'updated_at' => '2025-04-02 12:15:00',
            ],
            [
                'id' => 29,
                'ma_don_hang' => 'DH029',
                'id_khach_hang' => 2,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 11,
                'id_dia_chi_nhan' => 29,
                'ten_nguoi_nhan' => 'Nguyễn Văn A',
                'so_dien_thoai' => '0123456789',
                'tien_hang' => 60000,
                'phi_ship' => 12000,
                'tong_tien' => 72000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-03 10:00:00',
                'updated_at' => '2025-04-03 10:00:00',
            ],
            [
                'id' => 30,
                'ma_don_hang' => 'DH030',
                'id_khach_hang' => 3,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 12,
                'id_dia_chi_nhan' => 30,
                'ten_nguoi_nhan' => 'Lê Minh Tuấn',
                'so_dien_thoai' => '0987654321',
                'tien_hang' => 80000,
                'phi_ship' => 10000,
                'tong_tien' => 90000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-05 15:30:00',
                'updated_at' => '2025-04-05 15:30:00',
            ],
            [
                'id' => 31,
                'ma_don_hang' => 'DH031',
                'id_khach_hang' => 1,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 2,
                'id_dia_chi_nhan' => 1, // Địa chỉ của Võ Văn Việt
                'ten_nguoi_nhan' => 'Võ Văn Việt',
                'so_dien_thoai' => '0123456780',
                'tien_hang' => 70000,
                'phi_ship' => 10000,
                'tong_tien' => 80000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-18 11:00:00',
                'updated_at' => '2025-03-18 11:00:00',
            ],
            [
                'id' => 32,
                'ma_don_hang' => 'DH032',
                'id_khach_hang' => 2,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 3,
                'id_dia_chi_nhan' => 4, // Địa chỉ của Nguyễn Văn A
                'ten_nguoi_nhan' => 'Nguyễn Văn A',
                'so_dien_thoai' => '0123456789',
                'tien_hang' => 90000,
                'phi_ship' => 12000,
                'tong_tien' => 102000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-20 14:30:00',
                'updated_at' => '2025-03-20 14:30:00',
            ],
            [
                'id' => 33,
                'ma_don_hang' => 'DH033',
                'id_khach_hang' => 3,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 4,
                'id_dia_chi_nhan' => 7, // Địa chỉ của Lê Minh Tuấn
                'ten_nguoi_nhan' => 'Lê Minh Tuấn',
                'so_dien_thoai' => '0987654321',
                'tien_hang' => 75000,
                'phi_ship' => 8000,
                'tong_tien' => 83000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-22 15:45:00',
                'updated_at' => '2025-03-22 15:45:00',
            ],
            [
                'id' => 34,
                'ma_don_hang' => 'DH034',
                'id_khach_hang' => 4,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 5,
                'id_dia_chi_nhan' => 10, // Địa chỉ của Trần Thị Hồng Nhung
                'ten_nguoi_nhan' => 'Trần Thị Hồng Nhung',
                'so_dien_thoai' => '0911223344',
                'tien_hang' => 85000,
                'phi_ship' => 10000,
                'tong_tien' => 95000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-25 09:00:00',
                'updated_at' => '2025-03-25 09:00:00',
            ],
            [
                'id' => 35,
                'ma_don_hang' => 'DH035',
                'id_khach_hang' => 5,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 6,
                'id_dia_chi_nhan' => 13, // Địa chỉ của Đặng Quốc Huy
                'ten_nguoi_nhan' => 'Đặng Quốc Huy',
                'so_dien_thoai' => '0933445566',
                'tien_hang' => 95000,
                'phi_ship' => 12000,
                'tong_tien' => 107000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-27 11:20:00',
                'updated_at' => '2025-03-27 11:20:00',
            ],
            [
                'id' => 36,
                'ma_don_hang' => 'DH036',
                'id_khach_hang' => 6,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 7,
                'id_dia_chi_nhan' => 16, // Địa chỉ của Phạm Thị Mai
                'ten_nguoi_nhan' => 'Phạm Thị Mai',
                'so_dien_thoai' => '0909887766',
                'tien_hang' => 105000,
                'phi_ship' => 10000,
                'tong_tien' => 115000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-29 16:45:00',
                'updated_at' => '2025-03-29 16:45:00',
            ],
            [
                'id' => 37,
                'ma_don_hang' => 'DH037',
                'id_khach_hang' => 7,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 8,
                'id_dia_chi_nhan' => 19, // Địa chỉ của Ngô Văn Lâm
                'ten_nguoi_nhan' => 'Ngô Văn Lâm',
                'so_dien_thoai' => '0966887799',
                'tien_hang' => 110000,
                'phi_ship' => 12000,
                'tong_tien' => 122000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-03-30 14:00:00',
                'updated_at' => '2025-03-30 14:00:00',
            ],
            [
                'id' => 38,
                'ma_don_hang' => 'DH038',
                'id_khach_hang' => 1,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 9,
                'id_dia_chi_nhan' => 2, // Địa chỉ khác của Võ Văn Việt
                'ten_nguoi_nhan' => 'Võ Văn Việt',
                'so_dien_thoai' => '0123456780',
                'tien_hang' => 65000,
                'phi_ship' => 10000,
                'tong_tien' => 75000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-02 12:15:00',
                'updated_at' => '2025-04-02 12:15:00',
            ],
            [
                'id' => 39,
                'ma_don_hang' => 'DH039',
                'id_khach_hang' => 2,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 10,
                'id_dia_chi_nhan' => 5, // Địa chỉ khác của Nguyễn Văn A
                'ten_nguoi_nhan' => 'Nguyễn Văn A',
                'so_dien_thoai' => '0123456789',
                'tien_hang' => 90000,
                'phi_ship' => 12000,
                'tong_tien' => 102000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-03 10:00:00',
                'updated_at' => '2025-04-03 10:00:00',
            ],
            [
                'id' => 40,
                'ma_don_hang' => 'DH040',
                'id_khach_hang' => 3,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 11,
                'id_dia_chi_nhan' => 8, // Địa chỉ khác của Lê Minh Tuấn
                'ten_nguoi_nhan' => 'Lê Minh Tuấn',
                'so_dien_thoai' => '0987654321',
                'tien_hang' => 85000,
                'phi_ship' => 10000,
                'tong_tien' => 95000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-05 15:30:00',
                'updated_at' => '2025-04-05 15:30:00',
            ],
            [
                'id' => 41,
                'ma_don_hang' => 'DH041',
                'id_khach_hang' => 4,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 13,
                'id_dia_chi_nhan' => 11, // Địa chỉ của Trần Thị Hồng Nhung
                'ten_nguoi_nhan' => 'Trần Thị Hồng Nhung',
                'so_dien_thoai' => '0911223344',
                'tien_hang' => 80000,
                'phi_ship' => 10000,
                'tong_tien' => 90000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-08 11:00:00',
                'updated_at' => '2025-04-08 11:00:00',
            ],
            [
                'id' => 42,
                'ma_don_hang' => 'DH042',
                'id_khach_hang' => 5,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 14,
                'id_dia_chi_nhan' => 14, // Địa chỉ của Đặng Quốc Huy
                'ten_nguoi_nhan' => 'Đặng Quốc Huy',
                'so_dien_thoai' => '0933445566',
                'tien_hang' => 95000,
                'phi_ship' => 12000,
                'tong_tien' => 107000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-09 12:30:00',
                'updated_at' => '2025-04-09 12:30:00',
            ],
            [
                'id' => 43,
                'ma_don_hang' => 'DH043',
                'id_khach_hang' => 6,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 15,
                'id_dia_chi_nhan' => 17, // Địa chỉ của Phạm Thị Mai
                'ten_nguoi_nhan' => 'Phạm Thị Mai',
                'so_dien_thoai' => '0909887766',
                'tien_hang' => 85000,
                'phi_ship' => 10000,
                'tong_tien' => 95000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-10 14:15:00',
                'updated_at' => '2025-04-10 14:15:00',
            ],
            [
                'id' => 44,
                'ma_don_hang' => 'DH044',
                'id_khach_hang' => 7,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 16,
                'id_dia_chi_nhan' => 19, // Địa chỉ của Ngô Văn Lâm
                'ten_nguoi_nhan' => 'Ngô Văn Lâm',
                'so_dien_thoai' => '0966887799',
                'tien_hang' => 90000,
                'phi_ship' => 12000,
                'tong_tien' => 102000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-11 15:45:00',
                'updated_at' => '2025-04-11 15:45:00',
            ],
            [
                'id' => 45,
                'ma_don_hang' => 'DH045',
                'id_khach_hang' => 1,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 17,
                'id_dia_chi_nhan' => 3, // Địa chỉ khác của Võ Văn Việt
                'ten_nguoi_nhan' => 'Võ Văn Việt',
                'so_dien_thoai' => '0123456780',
                'tien_hang' => 100000,
                'phi_ship' => 10000,
                'tong_tien' => 110000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-12 17:00:00',
                'updated_at' => '2025-04-12 17:00:00',
            ],
            [
                'id' => 46,
                'ma_don_hang' => 'DH046',
                'id_khach_hang' => 2,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 18,
                'id_dia_chi_nhan' => 6, // Địa chỉ khác của Nguyễn Văn A
                'ten_nguoi_nhan' => 'Nguyễn Văn A',
                'so_dien_thoai' => '0123456789',
                'tien_hang' => 75000,
                'phi_ship' => 12000,
                'tong_tien' => 87000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-13 09:00:00',
                'updated_at' => '2025-04-13 09:00:00',
            ],
            [
                'id' => 47,
                'ma_don_hang' => 'DH047',
                'id_khach_hang' => 3,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 19,
                'id_dia_chi_nhan' => 9, // Địa chỉ khác của Lê Minh Tuấn
                'ten_nguoi_nhan' => 'Lê Minh Tuấn',
                'so_dien_thoai' => '0987654321',
                'tien_hang' => 85000,
                'phi_ship' => 10000,
                'tong_tien' => 95000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-14 14:30:00',
                'updated_at' => '2025-04-14 14:30:00',
            ],
            [
                'id' => 48,
                'ma_don_hang' => 'DH048',
                'id_khach_hang' => 4,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 20,
                'id_dia_chi_nhan' => 12, // Địa chỉ khác của Trần Thị Hồng Nhung
                'ten_nguoi_nhan' => 'Trần Thị Hồng Nhung',
                'so_dien_thoai' => '0911223344',
                'tien_hang' => 90000,
                'phi_ship' => 12000,
                'tong_tien' => 102000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-15 16:00:00',
                'updated_at' => '2025-04-15 16:00:00',
            ],
            [
                'id' => 49,
                'ma_don_hang' => 'DH049',
                'id_khach_hang' => 5,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 1,
                'id_dia_chi_nhan' => 15, // Địa chỉ khác của Đặng Quốc Huy
                'ten_nguoi_nhan' => 'Đặng Quốc Huy',
                'so_dien_thoai' => '0933445566',
                'tien_hang' => 95000,
                'phi_ship' => 12000,
                'tong_tien' => 107000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-16 11:30:00',
                'updated_at' => '2025-04-16 11:30:00',
            ],
            [
                'id' => 50,
                'ma_don_hang' => 'DH050',
                'id_khach_hang' => 6,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 2,
                'id_dia_chi_nhan' => 18, // Địa chỉ khác của Phạm Thị Mai
                'ten_nguoi_nhan' => 'Phạm Thị Mai',
                'so_dien_thoai' => '0909887766',
                'tien_hang' => 100000,
                'phi_ship' => 10000,
                'tong_tien' => 110000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-17 13:00:00',
                'updated_at' => '2025-04-17 13:00:00',
            ],
            [
                'id' => 51,
                'ma_don_hang' => 'DH051',
                'id_khach_hang' => 7,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 3,
                'id_dia_chi_nhan' => 20, // Địa chỉ của Ngô Văn Lâm
                'ten_nguoi_nhan' => 'Ngô Văn Lâm',
                'so_dien_thoai' => '0966887799',
                'tien_hang' => 75000,
                'phi_ship' => 10000,
                'tong_tien' => 85000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 11:00:00',
                'updated_at' => '2025-04-18 11:00:00',
            ],
            [
                'id' => 52,
                'ma_don_hang' => 'DH052',
                'id_khach_hang' => 1,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 4,
                'id_dia_chi_nhan' => 1, // Địa chỉ của Võ Văn Việt
                'ten_nguoi_nhan' => 'Võ Văn Việt',
                'so_dien_thoai' => '0123456780',
                'tien_hang' => 65000,
                'phi_ship' => 12000,
                'tong_tien' => 77000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 12:15:00',
                'updated_at' => '2025-04-18 12:15:00',
            ],
            [
                'id' => 53,
                'ma_don_hang' => 'DH053',
                'id_khach_hang' => 2,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 5,
                'id_dia_chi_nhan' => 5, // Địa chỉ của Nguyễn Văn A
                'ten_nguoi_nhan' => 'Nguyễn Văn A',
                'so_dien_thoai' => '0123456789',
                'tien_hang' => 80000,
                'phi_ship' => 10000,
                'tong_tien' => 90000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 13:30:00',
                'updated_at' => '2025-04-18 13:30:00',
            ],
            [
                'id' => 54,
                'ma_don_hang' => 'DH054',
                'id_khach_hang' => 3,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 6,
                'id_dia_chi_nhan' => 8, // Địa chỉ của Lê Minh Tuấn
                'ten_nguoi_nhan' => 'Lê Minh Tuấn',
                'so_dien_thoai' => '0987654321',
                'tien_hang' => 85000,
                'phi_ship' => 12000,
                'tong_tien' => 97000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 14:45:00',
                'updated_at' => '2025-04-18 14:45:00',
            ],
            [
                'id' => 55,
                'ma_don_hang' => 'DH055',
                'id_khach_hang' => 4,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 7,
                'id_dia_chi_nhan' => 12, // Địa chỉ của Trần Thị Hồng Nhung
                'ten_nguoi_nhan' => 'Trần Thị Hồng Nhung',
                'so_dien_thoai' => '0911223344',
                'tien_hang' => 90000,
                'phi_ship' => 10000,
                'tong_tien' => 100000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 16:00:00',
                'updated_at' => '2025-04-18 16:00:00',
            ],
            [
                'id' => 56,
                'ma_don_hang' => 'DH056',
                'id_khach_hang' => 5,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 8,
                'id_dia_chi_nhan' => 14, // Địa chỉ của Đặng Quốc Huy
                'ten_nguoi_nhan' => 'Đặng Quốc Huy',
                'so_dien_thoai' => '0933445566',
                'tien_hang' => 95000,
                'phi_ship' => 12000,
                'tong_tien' => 107000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 17:15:00',
                'updated_at' => '2025-04-18 17:15:00',
            ],
            [
                'id' => 57,
                'ma_don_hang' => 'DH057',
                'id_khach_hang' => 6,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 9,
                'id_dia_chi_nhan' => 17, // Địa chỉ của Phạm Thị Mai
                'ten_nguoi_nhan' => 'Phạm Thị Mai',
                'so_dien_thoai' => '0909887766',
                'tien_hang' => 80000,
                'phi_ship' => 10000,
                'tong_tien' => 90000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 18:30:00',
                'updated_at' => '2025-04-18 18:30:00',
            ],
            [
                'id' => 58,
                'ma_don_hang' => 'DH058',
                'id_khach_hang' => 7,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 10,
                'id_dia_chi_nhan' => 21, // Địa chỉ của Ngô Văn Lâm
                'ten_nguoi_nhan' => 'Ngô Văn Lâm',
                'so_dien_thoai' => '0966887799',
                'tien_hang' => 75000,
                'phi_ship' => 12000,
                'tong_tien' => 87000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 19:45:00',
                'updated_at' => '2025-04-18 19:45:00',
            ],
            [
                'id' => 59,
                'ma_don_hang' => 'DH059',
                'id_khach_hang' => 1,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 11,
                'id_dia_chi_nhan' => 2, // Địa chỉ khác của Võ Văn Việt
                'ten_nguoi_nhan' => 'Võ Văn Việt',
                'so_dien_thoai' => '0123456780',
                'tien_hang' => 70000,
                'phi_ship' => 10000,
                'tong_tien' => 80000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 20:00:00',
                'updated_at' => '2025-04-18 20:00:00',
            ],
            [
                'id' => 60,
                'ma_don_hang' => 'DH060',
                'id_khach_hang' => 2,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 12,
                'id_dia_chi_nhan' => 6, // Địa chỉ khác của Nguyễn Văn A
                'ten_nguoi_nhan' => 'Nguyễn Văn A',
                'so_dien_thoai' => '0123456789',
                'tien_hang' => 90000,
                'phi_ship' => 12000,
                'tong_tien' => 102000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 21:15:00',
                'updated_at' => '2025-04-18 21:15:00',
            ],
            [
                'id' => 61,
                'ma_don_hang' => 'DH061',
                'id_khach_hang' => 3,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 13,
                'id_dia_chi_nhan' => 7, // Địa chỉ của Lê Minh Tuấn
                'ten_nguoi_nhan' => 'Lê Minh Tuấn',
                'so_dien_thoai' => '0987654321',
                'tien_hang' => 88000,
                'phi_ship' => 10000,
                'tong_tien' => 98000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 11:00:00',
                'updated_at' => '2025-04-18 11:00:00',
            ],
            [
                'id' => 62,
                'ma_don_hang' => 'DH062',
                'id_khach_hang' => 4,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 14,
                'id_dia_chi_nhan' => 11, // Địa chỉ của Trần Thị Hồng Nhung
                'ten_nguoi_nhan' => 'Trần Thị Hồng Nhung',
                'so_dien_thoai' => '0911223344',
                'tien_hang' => 75000,
                'phi_ship' => 12000,
                'tong_tien' => 87000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 12:00:00',
                'updated_at' => '2025-04-18 12:00:00',
            ],
            [
                'id' => 63,
                'ma_don_hang' => 'DH063',
                'id_khach_hang' => 5,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 15,
                'id_dia_chi_nhan' => 15, // Địa chỉ của Đặng Quốc Huy
                'ten_nguoi_nhan' => 'Đặng Quốc Huy',
                'so_dien_thoai' => '0933445566',
                'tien_hang' => 94000,
                'phi_ship' => 12000,
                'tong_tien' => 106000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 13:00:00',
                'updated_at' => '2025-04-18 13:00:00',
            ],
            [
                'id' => 64,
                'ma_don_hang' => 'DH064',
                'id_khach_hang' => 6,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 16,
                'id_dia_chi_nhan' => 16, // Địa chỉ của Phạm Thị Mai
                'ten_nguoi_nhan' => 'Phạm Thị Mai',
                'so_dien_thoai' => '0909887766',
                'tien_hang' => 81000,
                'phi_ship' => 10000,
                'tong_tien' => 91000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 14:00:00',
                'updated_at' => '2025-04-18 14:00:00',
            ],
            [
                'id' => 65,
                'ma_don_hang' => 'DH065',
                'id_khach_hang' => 7,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 17,
                'id_dia_chi_nhan' => 19, // Địa chỉ của Ngô Văn Lâm
                'ten_nguoi_nhan' => 'Ngô Văn Lâm',
                'so_dien_thoai' => '0966887799',
                'tien_hang' => 85000,
                'phi_ship' => 12000,
                'tong_tien' => 97000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 15:00:00',
                'updated_at' => '2025-04-18 15:00:00',
            ],
            [
                'id' => 66,
                'ma_don_hang' => 'DH066',
                'id_khach_hang' => 1,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 18,
                'id_dia_chi_nhan' => 3, // Địa chỉ khác của Võ Văn Việt
                'ten_nguoi_nhan' => 'Võ Văn Việt',
                'so_dien_thoai' => '0123456780',
                'tien_hang' => 78000,
                'phi_ship' => 10000,
                'tong_tien' => 88000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 16:00:00',
                'updated_at' => '2025-04-18 16:00:00',
            ],
            [
                'id' => 67,
                'ma_don_hang' => 'DH067',
                'id_khach_hang' => 2,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 19,
                'id_dia_chi_nhan' => 6, // Địa chỉ khác của Nguyễn Văn A
                'ten_nguoi_nhan' => 'Nguyễn Văn A',
                'so_dien_thoai' => '0123456789',
                'tien_hang' => 92000,
                'phi_ship' => 12000,
                'tong_tien' => 104000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 17:00:00',
                'updated_at' => '2025-04-18 17:00:00',
            ],
            [
                'id' => 68,
                'ma_don_hang' => 'DH068',
                'id_khach_hang' => 3,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 20,
                'id_dia_chi_nhan' => 9, // Địa chỉ khác của Lê Minh Tuấn
                'ten_nguoi_nhan' => 'Lê Minh Tuấn',
                'so_dien_thoai' => '0987654321',
                'tien_hang' => 88000,
                'phi_ship' => 10000,
                'tong_tien' => 98000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 18:00:00',
                'updated_at' => '2025-04-18 18:00:00',
            ],
            [
                'id' => 69,
                'ma_don_hang' => 'DH069',
                'id_khach_hang' => 4,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 1,
                'id_dia_chi_nhan' => 10, // Địa chỉ khác của Trần Thị Hồng Nhung
                'ten_nguoi_nhan' => 'Trần Thị Hồng Nhung',
                'so_dien_thoai' => '0911223344',
                'tien_hang' => 93000,
                'phi_ship' => 10000,
                'tong_tien' => 103000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 19:00:00',
                'updated_at' => '2025-04-18 19:00:00',
            ],
            [
                'id' => 70,
                'ma_don_hang' => 'DH070',
                'id_khach_hang' => 5,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 2,
                'id_dia_chi_nhan' => 14, // Địa chỉ khác của Đặng Quốc Huy
                'ten_nguoi_nhan' => 'Đặng Quốc Huy',
                'so_dien_thoai' => '0933445566',
                'tien_hang' => 97000,
                'phi_ship' => 12000,
                'tong_tien' => 109000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 3,
                'created_at' => '2025-04-18 20:00:00',
                'updated_at' => '2025-04-18 20:00:00',
            ],
        ]);

        $data = DonHang::all();
        foreach ($data as $key => $value) {
            $value->ma_don_hang = "DH" . time() + $value->id;
            $tinh_trang = random_int(0, 3);
            $value->tinh_trang = $tinh_trang;
            if ($tinh_trang == 0) {
                $value->is_thanh_toan = 0;
            } else {
                $value->is_thanh_toan = random_int(0, 1);
            }
            $value->tien_hang = ceil(random_int(1000, 3000) / 100) * 100;
            $value->phi_ship  = ceil(random_int(500, 1000) / 100) * 100;
            $value->tong_tien = $value->tien_hang + $value->phi_ship;
            $value->save();
        }
    }
}
