<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuanHuyenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('quan_huyens')->delete();

        DB::table('quan_huyens')->truncate();

        DB::table('quan_huyens')->insert([
            ['ten_quan_huyen' => 'Quận Ba Đình', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Quận Bắc Từ Liêm', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Quận Cầu Giấy', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Quận Đống Đa', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Quận Hà Đông', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Quận Hai Bà Trưng', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Quận Hoàn Kiếm', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Quận Hoàng Mai', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Quận Long Biên', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Quận Nam Từ Liêm', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Quận Tây Hồ', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Quận Thanh Xuân', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Thị xã Sơn Tây', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Huyện Ba Vì', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Huyện Chương Mỹ', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Huyện Đan Phượng', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Huyện Đông Anh', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Huyện Gia Lâm', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Huyện Hoài Đức', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Huyện Mê Linh', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Huyện Mỹ Đức', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Huyện Phú Xuyên', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Huyện Phúc Thọ', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Huyện Quốc Oai', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Huyện Sóc Sơn', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Huyện Thạch Thất', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Huyện Thanh Oai', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Huyện Thanh Trì', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Huyện Thường Tín', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Huyện Ứng Hòa', 'id_tinh_thanh' => '3'],
            ['ten_quan_huyen' => 'Thành phố Thủ Đức', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Quận 1', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Quận 3', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Quận 4', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Quận 5', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Quận 6', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Quận 7', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Quận 8', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Quận 10', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Quận 11', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Quận 12', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Quận Bình Tân', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Quận Bình Thạnh', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Quận Gò Vấp', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Quận Phú Nhuận', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Quận Tân Bình', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Quận Tân Phú', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Huyện Bình Chánh', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Huyện Cần Giờ', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Huyện Củ Chi', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Huyện Hóc Môn', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Huyện Nhà Bè', 'id_tinh_thanh' => '4'],
            ['ten_quan_huyen' => 'Quận Cẩm Lệ', 'id_tinh_thanh' => '2'],
            ['ten_quan_huyen' => 'Quận Hải Châu', 'id_tinh_thanh' => '2'],
            ['ten_quan_huyen' => 'Quận Liên Chiểu', 'id_tinh_thanh' => '2'],
            ['ten_quan_huyen' => 'Quận Ngũ Hành Sơn', 'id_tinh_thanh' => '2'],
            ['ten_quan_huyen' => 'Quận Sơn Trà', 'id_tinh_thanh' => '2'],
            ['ten_quan_huyen' => 'Quận Thanh Khê', 'id_tinh_thanh' => '2'],
            ['ten_quan_huyen' => 'Huyện Hòa Vang', 'id_tinh_thanh' => '2'],
            ['ten_quan_huyen' => 'Huyện Hoàng Sa', 'id_tinh_thanh' => '2'],
            ['ten_quan_huyen' => 'Quận Bình Thủy', 'id_tinh_thanh' => '5'],
            ['ten_quan_huyen' => 'Quận Cái Răng', 'id_tinh_thanh' => '5'],
            ['ten_quan_huyen' => 'Quận Ninh Kiều', 'id_tinh_thanh' => '5'],
            ['ten_quan_huyen' => 'Quận Ô Môn', 'id_tinh_thanh' => '5'],
            ['ten_quan_huyen' => 'Quận Thốt Nốt', 'id_tinh_thanh' => '5'],
            ['ten_quan_huyen' => 'Huyện Cờ Đỏ', 'id_tinh_thanh' => '5'],
            ['ten_quan_huyen' => 'Huyện Phong Điền', 'id_tinh_thanh' => '5'],
            ['ten_quan_huyen' => 'Huyện Thới Lai', 'id_tinh_thanh' => '5'],
            ['ten_quan_huyen' => 'Huyện Vĩnh Thạnh', 'id_tinh_thanh' => '5'],
            ['ten_quan_huyen' => 'Quận Đồ Sơn', 'id_tinh_thanh' => '6'],
            ['ten_quan_huyen' => 'Quận Dương Kinh', 'id_tinh_thanh' => '6'],
            ['ten_quan_huyen' => 'Quận Hải An', 'id_tinh_thanh' => '6'],
            ['ten_quan_huyen' => 'Quận Hồng Bàng', 'id_tinh_thanh' => '6'],
            ['ten_quan_huyen' => 'Quận Kiến An', 'id_tinh_thanh' => '6'],
            ['ten_quan_huyen' => 'Quận Lê Chân', 'id_tinh_thanh' => '6'],
            ['ten_quan_huyen' => 'Quận Ngô Quyền', 'id_tinh_thanh' => '6'],
            ['ten_quan_huyen' => 'Huyện An Dương', 'id_tinh_thanh' => '6'],
            ['ten_quan_huyen' => 'Huyện An Lão', 'id_tinh_thanh' => '6'],
            ['ten_quan_huyen' => 'Huyện Bạch Long Vĩ', 'id_tinh_thanh' => '6'],
            ['ten_quan_huyen' => 'Huyện Cát Hải', 'id_tinh_thanh' => '6'],
            ['ten_quan_huyen' => 'Huyện Kiến Thụy', 'id_tinh_thanh' => '6'],
            ['ten_quan_huyen' => 'Huyện Thủy Nguyên', 'id_tinh_thanh' => '6'],
            ['ten_quan_huyen' => 'Huyện Tiên Lãng', 'id_tinh_thanh' => '6'],
            ['ten_quan_huyen' => 'Huyện Vĩnh Bảo', 'id_tinh_thanh' => '6'],
            ['ten_quan_huyen' => 'Thành phố Long Xuyên (tỉnh lỵ)', 'id_tinh_thanh' => '7'],
            ['ten_quan_huyen' => 'Thành phố Châu Đốc', 'id_tinh_thanh' => '7'],
            ['ten_quan_huyen' => 'Thị xã Tân Châu', 'id_tinh_thanh' => '7'],
            ['ten_quan_huyen' => 'Huyện An Phú', 'id_tinh_thanh' => '7'],
            ['ten_quan_huyen' => 'Huyện Châu Phú', 'id_tinh_thanh' => '7'],
            ['ten_quan_huyen' => 'Huyện Châu Thành', 'id_tinh_thanh' => '7'],
            ['ten_quan_huyen' => 'Huyện Chợ Mới', 'id_tinh_thanh' => '7'],
            ['ten_quan_huyen' => 'Huyện Phú Tân', 'id_tinh_thanh' => '7'],
            ['ten_quan_huyen' => 'Huyện Thoại Sơn', 'id_tinh_thanh' => '7'],
            ['ten_quan_huyen' => 'Huyện Tịnh Biên', 'id_tinh_thanh' => '7'],
            ['ten_quan_huyen' => 'Huyện Tri Tôn', 'id_tinh_thanh' => '7'],
            ['ten_quan_huyen' => 'Thành phố Bà Rịa (tỉnh lỵ)', 'id_tinh_thanh' => '8'],
            ['ten_quan_huyen' => 'Thành phố Vũng Tàu', 'id_tinh_thanh' => '8'],
            ['ten_quan_huyen' => 'Thị xã Phú Mỹ', 'id_tinh_thanh' => '8'],
            ['ten_quan_huyen' => 'Huyện Châu Đức', 'id_tinh_thanh' => '8'],
            ['ten_quan_huyen' => 'Huyện Côn Đảo', 'id_tinh_thanh' => '8'],
            ['ten_quan_huyen' => 'Huyện Đất Đỏ', 'id_tinh_thanh' => '8'],
            ['ten_quan_huyen' => 'Huyện Long Điền', 'id_tinh_thanh' => '8'],
            ['ten_quan_huyen' => 'Huyện Xuyên Mộc', 'id_tinh_thanh' => '8'],
            ['ten_quan_huyen' => 'Thành phố Bắc Giang (tỉnh lỵ)', 'id_tinh_thanh' => '9'],
            ['ten_quan_huyen' => 'Huyện Hiệp Hòa', 'id_tinh_thanh' => '9'],
            ['ten_quan_huyen' => 'Huyện Lạng Giang', 'id_tinh_thanh' => '9'],
            ['ten_quan_huyen' => 'Huyện Lục Nam', 'id_tinh_thanh' => '9'],
            ['ten_quan_huyen' => 'Huyện Lục Ngạn', 'id_tinh_thanh' => '9'],
            ['ten_quan_huyen' => 'Huyện Sơn Động', 'id_tinh_thanh' => '9'],
            ['ten_quan_huyen' => 'Huyện Tân Yên', 'id_tinh_thanh' => '9'],
            ['ten_quan_huyen' => 'Huyện Việt Yên', 'id_tinh_thanh' => '9'],
            ['ten_quan_huyen' => 'Huyện Yên Dũng', 'id_tinh_thanh' => '9'],
            ['ten_quan_huyen' => 'Huyện Yên Thế', 'id_tinh_thanh' => '9'],
            ['ten_quan_huyen' => 'Thành phố Bắc Kạn (tỉnh lỵ)', 'id_tinh_thanh' => '10'],
            ['ten_quan_huyen' => 'Huyện Ba Bể', 'id_tinh_thanh' => '10'],
            ['ten_quan_huyen' => 'Huyện Bạch Thông', 'id_tinh_thanh' => '10'],
            ['ten_quan_huyen' => 'Huyện Chợ Đồn', 'id_tinh_thanh' => '10'],
            ['ten_quan_huyen' => 'Huyện Chợ Mới', 'id_tinh_thanh' => '10'],
            ['ten_quan_huyen' => 'Huyện Na Rì', 'id_tinh_thanh' => '10'],
            ['ten_quan_huyen' => 'Huyện Ngân Sơn', 'id_tinh_thanh' => '10'],
            ['ten_quan_huyen' => 'Huyện Pác Nặm', 'id_tinh_thanh' => '10'],
            ['ten_quan_huyen' => 'Thành phố Bạc Liêu (tỉnh lỵ)', 'id_tinh_thanh' => '11'],
            ['ten_quan_huyen' => 'Thị xã Giá Rai', 'id_tinh_thanh' => '11'],
            ['ten_quan_huyen' => 'Huyện Đông Hải', 'id_tinh_thanh' => '11'],
            ['ten_quan_huyen' => 'Huyện Hòa Bình', 'id_tinh_thanh' => '11'],
            ['ten_quan_huyen' => 'Huyện Hồng Dân', 'id_tinh_thanh' => '11'],
            ['ten_quan_huyen' => 'Huyện Phước Long', 'id_tinh_thanh' => '11'],
            ['ten_quan_huyen' => 'Huyện Vĩnh Lợi', 'id_tinh_thanh' => '11'],
            ['ten_quan_huyen' => 'Thành phố Bắc Ninh (tỉnh lỵ)', 'id_tinh_thanh' => '12'],
            ['ten_quan_huyen' => 'Thị xã Từ Sơn', 'id_tinh_thanh' => '12'],
            ['ten_quan_huyen' => 'Huyện Gia Bình', 'id_tinh_thanh' => '12'],
            ['ten_quan_huyen' => 'Huyện Lương Tài', 'id_tinh_thanh' => '12'],
            ['ten_quan_huyen' => 'Huyện Quế Võ', 'id_tinh_thanh' => '12'],
            ['ten_quan_huyen' => 'Huyện Thuận Thành', 'id_tinh_thanh' => '12'],
            ['ten_quan_huyen' => 'Huyện Tiên Du', 'id_tinh_thanh' => '12'],
            ['ten_quan_huyen' => 'Huyện Yên Phong', 'id_tinh_thanh' => '12'],
            ['ten_quan_huyen' => 'Thành phố Bến Tre (tỉnh lỵ)', 'id_tinh_thanh' => '13'],
            ['ten_quan_huyen' => 'Huyện Ba Tri', 'id_tinh_thanh' => '13'],
            ['ten_quan_huyen' => 'Huyện Bình Đại', 'id_tinh_thanh' => '13'],
            ['ten_quan_huyen' => 'Huyện Châu Thành', 'id_tinh_thanh' => '13'],
            ['ten_quan_huyen' => 'Huyện Chợ Lách', 'id_tinh_thanh' => '13'],
            ['ten_quan_huyen' => 'Huyện Giồng Trôm', 'id_tinh_thanh' => '13'],
            ['ten_quan_huyen' => 'Huyện Mỏ Cày Bắc', 'id_tinh_thanh' => '13'],
            ['ten_quan_huyen' => 'Huyện Mỏ Cày Nam', 'id_tinh_thanh' => '13'],
            ['ten_quan_huyen' => 'Huyện Thạnh Phú', 'id_tinh_thanh' => '13'],
            ['ten_quan_huyen' => 'Thành phố Quy Nhơn (tỉnh lỵ)', 'id_tinh_thanh' => '14'],
            ['ten_quan_huyen' => 'Thị xã An Nhơn', 'id_tinh_thanh' => '14'],
            ['ten_quan_huyen' => 'Thị xã Hoài Nhơn', 'id_tinh_thanh' => '14'],
            ['ten_quan_huyen' => 'Huyện An Lão', 'id_tinh_thanh' => '14'],
            ['ten_quan_huyen' => 'Huyện Hoài Ân', 'id_tinh_thanh' => '14'],
            ['ten_quan_huyen' => 'Huyện Phù Cát', 'id_tinh_thanh' => '14'],
            ['ten_quan_huyen' => 'Huyện Phù Mỹ', 'id_tinh_thanh' => '14'],
            ['ten_quan_huyen' => 'Huyện Tây Sơn', 'id_tinh_thanh' => '14'],
            ['ten_quan_huyen' => 'Huyện Tuy Phước', 'id_tinh_thanh' => '14'],
            ['ten_quan_huyen' => 'Huyện Vân Canh', 'id_tinh_thanh' => '14'],
            ['ten_quan_huyen' => 'Huyện Vĩnh Thạnh', 'id_tinh_thanh' => '14'],
            ['ten_quan_huyen' => 'Thành phố Thủ Dầu Một (tỉnh lỵ)', 'id_tinh_thanh' => '15'],
            ['ten_quan_huyen' => 'Thành phố Dĩ An', 'id_tinh_thanh' => '15'],
            ['ten_quan_huyen' => 'Thành phố Thuận An', 'id_tinh_thanh' => '15'],
            ['ten_quan_huyen' => 'Thị xã Bến Cát', 'id_tinh_thanh' => '15'],
            ['ten_quan_huyen' => 'Thị xã Tân Uyên', 'id_tinh_thanh' => '15'],
            ['ten_quan_huyen' => 'Huyện Bắc Tân Uyên', 'id_tinh_thanh' => '15'],
            ['ten_quan_huyen' => 'Huyện Bàu Bàng', 'id_tinh_thanh' => '15'],
            ['ten_quan_huyen' => 'Huyện Dầu Tiếng', 'id_tinh_thanh' => '15'],
            ['ten_quan_huyen' => 'Huyện Phú Giáo', 'id_tinh_thanh' => '15'],
            ['ten_quan_huyen' => 'Thành phố Đồng Xoài (tỉnh lỵ)', 'id_tinh_thanh' => '16'],
            ['ten_quan_huyen' => 'Thị xã Bình Long', 'id_tinh_thanh' => '16'],
            ['ten_quan_huyen' => 'Thị xã Phước Long', 'id_tinh_thanh' => '16'],
            ['ten_quan_huyen' => 'Huyện Bù Đăng', 'id_tinh_thanh' => '16'],
            ['ten_quan_huyen' => 'Huyện Bù Đốp', 'id_tinh_thanh' => '16'],
            ['ten_quan_huyen' => 'Huyện Bù Gia Mập', 'id_tinh_thanh' => '16'],
            ['ten_quan_huyen' => 'Huyện Chơn Thành', 'id_tinh_thanh' => '16'],
            ['ten_quan_huyen' => 'Huyện Đồng Phú', 'id_tinh_thanh' => '16'],
            ['ten_quan_huyen' => 'Huyện Hớn Quản', 'id_tinh_thanh' => '16'],
            ['ten_quan_huyen' => 'Huyện Lộc Ninh', 'id_tinh_thanh' => '16'],
            ['ten_quan_huyen' => 'Huyện Phú Riềng', 'id_tinh_thanh' => '16'],
            ['ten_quan_huyen' => 'Thành phố Phan Thiết (tỉnh lỵ)', 'id_tinh_thanh' => '17'],
            ['ten_quan_huyen' => 'Thị xã La Gi', 'id_tinh_thanh' => '17'],
            ['ten_quan_huyen' => 'Huyện Bắc Bình', 'id_tinh_thanh' => '17'],
            ['ten_quan_huyen' => 'Huyện Đức Linh', 'id_tinh_thanh' => '17'],
            ['ten_quan_huyen' => 'Huyện Hàm Tân', 'id_tinh_thanh' => '17'],
            ['ten_quan_huyen' => 'Huyện Hàm Thuận Bắc', 'id_tinh_thanh' => '17'],
            ['ten_quan_huyen' => 'Huyện Hàm Thuận Nam', 'id_tinh_thanh' => '17'],
            ['ten_quan_huyen' => 'Huyện Phú Quý', 'id_tinh_thanh' => '17'],
            ['ten_quan_huyen' => 'Huyện Tánh Linh', 'id_tinh_thanh' => '17'],
            ['ten_quan_huyen' => 'Huyện Tuy Phong', 'id_tinh_thanh' => '17'],
            ['ten_quan_huyen' => 'Thành phố Cà Mau (tỉnh lỵ)', 'id_tinh_thanh' => '18'],
            ['ten_quan_huyen' => 'Huyện Cái Nước', 'id_tinh_thanh' => '18'],
            ['ten_quan_huyen' => 'Huyện Đầm Dơi', 'id_tinh_thanh' => '18'],
            ['ten_quan_huyen' => 'Huyện Năm Căn', 'id_tinh_thanh' => '18'],
            ['ten_quan_huyen' => 'Huyện Ngọc Hiển', 'id_tinh_thanh' => '18'],
            ['ten_quan_huyen' => 'Huyện Phú Tân', 'id_tinh_thanh' => '18'],
            ['ten_quan_huyen' => 'Huyện Thới Bình', 'id_tinh_thanh' => '18'],
            ['ten_quan_huyen' => 'Huyện Trần Văn Thời', 'id_tinh_thanh' => '18'],
            ['ten_quan_huyen' => 'Huyện U Minh', 'id_tinh_thanh' => '18'],
            ['ten_quan_huyen' => 'Thành phố Cao Bằng (tỉnh lỵ)', 'id_tinh_thanh' => '19'],
            ['ten_quan_huyen' => 'Huyện Bảo Lạc', 'id_tinh_thanh' => '19'],
            ['ten_quan_huyen' => 'Huyện Bảo Lâm', 'id_tinh_thanh' => '19'],
            ['ten_quan_huyen' => 'Huyện Hạ Lang', 'id_tinh_thanh' => '19'],
            ['ten_quan_huyen' => 'Huyện Hà Quảng', 'id_tinh_thanh' => '19'],
            ['ten_quan_huyen' => 'Huyện Hòa An', 'id_tinh_thanh' => '19'],
            ['ten_quan_huyen' => 'Huyện Nguyên Bình', 'id_tinh_thanh' => '19'],
            ['ten_quan_huyen' => 'Huyện Quảng Hòa', 'id_tinh_thanh' => '19'],
            ['ten_quan_huyen' => 'Huyện Thạch An', 'id_tinh_thanh' => '19'],
            ['ten_quan_huyen' => 'Huyện Trùng Khánh', 'id_tinh_thanh' => '19'],
            ['ten_quan_huyen' => 'Thành phố Buôn Ma Thuột (tỉnh lỵ)', 'id_tinh_thanh' => '20'],
            ['ten_quan_huyen' => 'Thị xã Buôn Hồ', 'id_tinh_thanh' => '20'],
            ['ten_quan_huyen' => 'Huyện Buôn Đôn', 'id_tinh_thanh' => '20'],
            ['ten_quan_huyen' => 'Huyện Cư Kuin', 'id_tinh_thanh' => '20'],
            ['ten_quan_huyen' => 'Huyện Cư Mxxgar', 'id_tinh_thanh' => '20'],
            ['ten_quan_huyen' => 'Huyện Ea Hxxleo', 'id_tinh_thanh' => '20'],
            ['ten_quan_huyen' => 'Huyện Ea Kar', 'id_tinh_thanh' => '20'],
            ['ten_quan_huyen' => 'Huyện Ea Súp', 'id_tinh_thanh' => '20'],
            ['ten_quan_huyen' => 'Huyện Krông Ana', 'id_tinh_thanh' => '20'],
            ['ten_quan_huyen' => 'Huyện Krông Bông', 'id_tinh_thanh' => '20'],
            ['ten_quan_huyen' => 'Huyện Krông Búk', 'id_tinh_thanh' => '20'],
            ['ten_quan_huyen' => 'Huyện Krông Năng', 'id_tinh_thanh' => '20'],
            ['ten_quan_huyen' => 'Huyện Krông Pắk', 'id_tinh_thanh' => '20'],
            ['ten_quan_huyen' => 'Huyện Lắk', 'id_tinh_thanh' => '20'],
            ['ten_quan_huyen' => 'Huyện MxxDrắk', 'id_tinh_thanh' => '20'],
            ['ten_quan_huyen' => 'Thành phố Gia Nghĩa (tỉnh lỵ)', 'id_tinh_thanh' => '21'],
            ['ten_quan_huyen' => 'Huyện Cư Jút', 'id_tinh_thanh' => '21'],
            ['ten_quan_huyen' => 'Huyện Đắk Glong', 'id_tinh_thanh' => '21'],
            ['ten_quan_huyen' => 'Huyện Đắk Mil', 'id_tinh_thanh' => '21'],
            ['ten_quan_huyen' => 'Huyện Đắk Rxxlấp', 'id_tinh_thanh' => '21'],
            ['ten_quan_huyen' => 'Huyện Đắk Song', 'id_tinh_thanh' => '21'],
            ['ten_quan_huyen' => 'Huyện Krông Nô', 'id_tinh_thanh' => '21'],
            ['ten_quan_huyen' => 'Huyện Tuy Đức', 'id_tinh_thanh' => '21'],
            ['ten_quan_huyen' => 'Thành phố Điện Biên Phủ (tỉnh lỵ)', 'id_tinh_thanh' => '22'],
            ['ten_quan_huyen' => 'Thị xã Mường Lay', 'id_tinh_thanh' => '22'],
            ['ten_quan_huyen' => 'Huyện Điện Biên', 'id_tinh_thanh' => '22'],
            ['ten_quan_huyen' => 'Huyện Điện Biên Đông', 'id_tinh_thanh' => '22'],
            ['ten_quan_huyen' => 'Huyện Mường Ảng', 'id_tinh_thanh' => '22'],
            ['ten_quan_huyen' => 'Huyện Mường Chà', 'id_tinh_thanh' => '22'],
            ['ten_quan_huyen' => 'Huyện Mường Nhé', 'id_tinh_thanh' => '22'],
            ['ten_quan_huyen' => 'Huyện Nậm Pồ', 'id_tinh_thanh' => '22'],
            ['ten_quan_huyen' => 'Huyện Tủa Chùa', 'id_tinh_thanh' => '22'],
            ['ten_quan_huyen' => 'Huyện Tuần Giáo', 'id_tinh_thanh' => '22'],
            ['ten_quan_huyen' => 'Thành phố Biên Hòa (tỉnh lỵ)', 'id_tinh_thanh' => '23'],
            ['ten_quan_huyen' => 'Thành phố Long Khánh', 'id_tinh_thanh' => '23'],
            ['ten_quan_huyen' => 'Huyện Cẩm Mỹ', 'id_tinh_thanh' => '23'],
            ['ten_quan_huyen' => 'Huyện Định Quán', 'id_tinh_thanh' => '23'],
            ['ten_quan_huyen' => 'Huyện Long Thành', 'id_tinh_thanh' => '23'],
            ['ten_quan_huyen' => 'Huyện Nhơn Trạch', 'id_tinh_thanh' => '23'],
            ['ten_quan_huyen' => 'Huyện Tân Phú', 'id_tinh_thanh' => '23'],
            ['ten_quan_huyen' => 'Huyện Thống Nhất', 'id_tinh_thanh' => '23'],
            ['ten_quan_huyen' => 'Huyện Trảng Bom', 'id_tinh_thanh' => '23'],
            ['ten_quan_huyen' => 'Huyện Vĩnh Cửu', 'id_tinh_thanh' => '23'],
            ['ten_quan_huyen' => 'Huyện Xuân Lộc', 'id_tinh_thanh' => '23'],
            ['ten_quan_huyen' => 'Thành phố Cao Lãnh (tỉnh lỵ)', 'id_tinh_thanh' => '24'],
            ['ten_quan_huyen' => 'Thành phố Hồng Ngự', 'id_tinh_thanh' => '24'],
            ['ten_quan_huyen' => 'Thành phố Sa Đéc', 'id_tinh_thanh' => '24'],
            ['ten_quan_huyen' => 'Huyện Cao Lãnh', 'id_tinh_thanh' => '24'],
            ['ten_quan_huyen' => 'Huyện Châu Thành', 'id_tinh_thanh' => '24'],
            ['ten_quan_huyen' => 'Huyện Hồng Ngự', 'id_tinh_thanh' => '24'],
            ['ten_quan_huyen' => 'Huyện Lai Vung', 'id_tinh_thanh' => '24'],
            ['ten_quan_huyen' => 'Huyện Lấp Vò', 'id_tinh_thanh' => '24'],
            ['ten_quan_huyen' => 'Huyện Tam Nông', 'id_tinh_thanh' => '24'],
            ['ten_quan_huyen' => 'Huyện Tân Hồng', 'id_tinh_thanh' => '24'],
            ['ten_quan_huyen' => 'Huyện Thanh Bình', 'id_tinh_thanh' => '24'],
            ['ten_quan_huyen' => 'Huyện Tháp Mười', 'id_tinh_thanh' => '24'],
            ['ten_quan_huyen' => 'Thành phố Pleiku (tỉnh lỵ)', 'id_tinh_thanh' => '25'],
            ['ten_quan_huyen' => 'Thị xã An Khê', 'id_tinh_thanh' => '25'],
            ['ten_quan_huyen' => 'Thị xã Ayun Pa', 'id_tinh_thanh' => '25'],
            ['ten_quan_huyen' => 'Huyện Chư Păh', 'id_tinh_thanh' => '25'],
            ['ten_quan_huyen' => 'Huyện Chư Prông', 'id_tinh_thanh' => '25'],
            ['ten_quan_huyen' => 'Huyện Chư Pưh', 'id_tinh_thanh' => '25'],
            ['ten_quan_huyen' => 'Huyện Chư Sê', 'id_tinh_thanh' => '25'],
            ['ten_quan_huyen' => 'Huyện Đak Đoa', 'id_tinh_thanh' => '25'],
            ['ten_quan_huyen' => 'Huyện Đak Pơ', 'id_tinh_thanh' => '25'],
            ['ten_quan_huyen' => 'Huyện Đức Cơ', 'id_tinh_thanh' => '25'],
            ['ten_quan_huyen' => 'Huyện Ia Grai', 'id_tinh_thanh' => '25'],
            ['ten_quan_huyen' => 'Huyện Ia Pa', 'id_tinh_thanh' => '25'],
            ['ten_quan_huyen' => 'Huyện Kbang', 'id_tinh_thanh' => '25'],
            ['ten_quan_huyen' => 'Huyện Kông Chro', 'id_tinh_thanh' => '25'],
            ['ten_quan_huyen' => 'Huyện Krông Pa', 'id_tinh_thanh' => '25'],
            ['ten_quan_huyen' => 'Huyện Mang Yang', 'id_tinh_thanh' => '25'],
            ['ten_quan_huyen' => 'Huyện Phú Thiện', 'id_tinh_thanh' => '25'],
            ['ten_quan_huyen' => 'Thành phố Hà Giang (tỉnh lỵ)', 'id_tinh_thanh' => '26'],
            ['ten_quan_huyen' => 'Huyện Bắc Mê', 'id_tinh_thanh' => '26'],
            ['ten_quan_huyen' => 'Huyện Bắc Quang', 'id_tinh_thanh' => '26'],
            ['ten_quan_huyen' => 'Huyện Đồng Văn', 'id_tinh_thanh' => '26'],
            ['ten_quan_huyen' => 'Huyện Hoàng Su Phì', 'id_tinh_thanh' => '26'],
            ['ten_quan_huyen' => 'Huyện Mèo Vạc', 'id_tinh_thanh' => '26'],
            ['ten_quan_huyen' => 'Huyện Quản Bạ', 'id_tinh_thanh' => '26'],
            ['ten_quan_huyen' => 'Huyện Quang Bình', 'id_tinh_thanh' => '26'],
            ['ten_quan_huyen' => 'Huyện Vị Xuyên', 'id_tinh_thanh' => '26'],
            ['ten_quan_huyen' => 'Huyện Xín Mần', 'id_tinh_thanh' => '26'],
            ['ten_quan_huyen' => 'Huyện Yên Minh', 'id_tinh_thanh' => '26'],
            ['ten_quan_huyen' => 'Thành phố Phủ Lý (tỉnh lỵ)', 'id_tinh_thanh' => '27'],
            ['ten_quan_huyen' => 'Thị xã Duy Tiên', 'id_tinh_thanh' => '27'],
            ['ten_quan_huyen' => 'Huyện Bình Lục', 'id_tinh_thanh' => '27'],
            ['ten_quan_huyen' => 'Huyện Kim Bảng', 'id_tinh_thanh' => '27'],
            ['ten_quan_huyen' => 'Huyện Lý Nhân', 'id_tinh_thanh' => '27'],
            ['ten_quan_huyen' => 'Huyện Thanh Liêm', 'id_tinh_thanh' => '27'],
            ['ten_quan_huyen' => 'Thành phố Hà Tĩnh (tỉnh lỵ)', 'id_tinh_thanh' => '28'],
            ['ten_quan_huyen' => 'Thị xã Hồng Lĩnh', 'id_tinh_thanh' => '28'],
            ['ten_quan_huyen' => 'Thị xã Kỳ Anh', 'id_tinh_thanh' => '28'],
            ['ten_quan_huyen' => 'Huyện Cẩm Xuyên', 'id_tinh_thanh' => '28'],
            ['ten_quan_huyen' => 'Huyện Can Lộc', 'id_tinh_thanh' => '28'],
            ['ten_quan_huyen' => 'Huyện Đức Thọ', 'id_tinh_thanh' => '28'],
            ['ten_quan_huyen' => 'Huyện Hương Khê', 'id_tinh_thanh' => '28'],
            ['ten_quan_huyen' => 'Huyện Hương Sơn', 'id_tinh_thanh' => '28'],
            ['ten_quan_huyen' => 'Huyện Kỳ Anh', 'id_tinh_thanh' => '28'],
            ['ten_quan_huyen' => 'Huyện Lộc Hà', 'id_tinh_thanh' => '28'],
            ['ten_quan_huyen' => 'Huyện Nghi Xuân', 'id_tinh_thanh' => '28'],
            ['ten_quan_huyen' => 'Huyện Thạch Hà', 'id_tinh_thanh' => '28'],
            ['ten_quan_huyen' => 'Huyện Vũ Quang', 'id_tinh_thanh' => '28'],
            ['ten_quan_huyen' => 'Thành phố Hải Dương (tỉnh lỵ)', 'id_tinh_thanh' => '29'],
            ['ten_quan_huyen' => 'Thành phố Chí Linh', 'id_tinh_thanh' => '29'],
            ['ten_quan_huyen' => 'Thị xã Kinh Môn', 'id_tinh_thanh' => '29'],
            ['ten_quan_huyen' => 'Huyện Bình Giang', 'id_tinh_thanh' => '29'],
            ['ten_quan_huyen' => 'Huyện Cẩm Giàng', 'id_tinh_thanh' => '29'],
            ['ten_quan_huyen' => 'Huyện Gia Lộc', 'id_tinh_thanh' => '29'],
            ['ten_quan_huyen' => 'Huyện Kim Thành', 'id_tinh_thanh' => '29'],
            ['ten_quan_huyen' => 'Huyện Nam Sách', 'id_tinh_thanh' => '29'],
            ['ten_quan_huyen' => 'Huyện Ninh Giang', 'id_tinh_thanh' => '29'],
            ['ten_quan_huyen' => 'Huyện Thanh Hà', 'id_tinh_thanh' => '29'],
            ['ten_quan_huyen' => 'Huyện Thanh Miện', 'id_tinh_thanh' => '29'],
            ['ten_quan_huyen' => 'Huyện Tứ Kỳ', 'id_tinh_thanh' => '29'],
            ['ten_quan_huyen' => 'Thành phố Vị Thanh (tỉnh lỵ)', 'id_tinh_thanh' => '30'],
            ['ten_quan_huyen' => 'Thành phố Ngã Bảy', 'id_tinh_thanh' => '30'],
            ['ten_quan_huyen' => 'Thị xã Long Mỹ', 'id_tinh_thanh' => '30'],
            ['ten_quan_huyen' => 'Huyện Châu Thành', 'id_tinh_thanh' => '30'],
            ['ten_quan_huyen' => 'Huyện Châu Thành A', 'id_tinh_thanh' => '30'],
            ['ten_quan_huyen' => 'Huyện Long Mỹ', 'id_tinh_thanh' => '30'],
            ['ten_quan_huyen' => 'Huyện Phụng Hiệp', 'id_tinh_thanh' => '30'],
            ['ten_quan_huyen' => 'Huyện Vị Thủy', 'id_tinh_thanh' => '30'],
            ['ten_quan_huyen' => 'Thành phố Hòa Bình (tỉnh lỵ)', 'id_tinh_thanh' => '31'],
            ['ten_quan_huyen' => 'Huyện Cao Phong', 'id_tinh_thanh' => '31'],
            ['ten_quan_huyen' => 'Huyện Đà Bắc', 'id_tinh_thanh' => '31'],
            ['ten_quan_huyen' => 'Huyện Kim Bôi', 'id_tinh_thanh' => '31'],
            ['ten_quan_huyen' => 'Huyện Lạc Sơn', 'id_tinh_thanh' => '31'],
            ['ten_quan_huyen' => 'Huyện Lạc Thủy', 'id_tinh_thanh' => '31'],
            ['ten_quan_huyen' => 'Huyện Lương Sơn', 'id_tinh_thanh' => '31'],
            ['ten_quan_huyen' => 'Huyện Mai Châu', 'id_tinh_thanh' => '31'],
            ['ten_quan_huyen' => 'Huyện Tân Lạc', 'id_tinh_thanh' => '31'],
            ['ten_quan_huyen' => 'Huyện Yên Thủy', 'id_tinh_thanh' => '31'],
            ['ten_quan_huyen' => 'Thành phố Hưng Yên (tỉnh lỵ)', 'id_tinh_thanh' => '32'],
            ['ten_quan_huyen' => 'Thị xã Mỹ Hào', 'id_tinh_thanh' => '32'],
            ['ten_quan_huyen' => 'Huyện Ân Thi', 'id_tinh_thanh' => '32'],
            ['ten_quan_huyen' => 'Huyện Khoái Châu', 'id_tinh_thanh' => '32'],
            ['ten_quan_huyen' => 'Huyện Kim Động', 'id_tinh_thanh' => '32'],
            ['ten_quan_huyen' => 'Huyện Phù Cừ', 'id_tinh_thanh' => '32'],
            ['ten_quan_huyen' => 'Huyện Tiên Lữ', 'id_tinh_thanh' => '32'],
            ['ten_quan_huyen' => 'Huyện Văn Giang', 'id_tinh_thanh' => '32'],
            ['ten_quan_huyen' => 'Huyện Văn Lâm', 'id_tinh_thanh' => '32'],
            ['ten_quan_huyen' => 'Huyện Yên Mỹ', 'id_tinh_thanh' => '32'],
            ['ten_quan_huyen' => 'Thành phố Nha Trang (tỉnh lỵ)', 'id_tinh_thanh' => '33'],
            ['ten_quan_huyen' => 'Thành phố Cam Ranh', 'id_tinh_thanh' => '33'],
            ['ten_quan_huyen' => 'Thị xã Ninh Hòa', 'id_tinh_thanh' => '33'],
            ['ten_quan_huyen' => 'Huyện Cam Lâm', 'id_tinh_thanh' => '33'],
            ['ten_quan_huyen' => 'Huyện Diên Khánh', 'id_tinh_thanh' => '33'],
            ['ten_quan_huyen' => 'Huyện Khánh Sơn', 'id_tinh_thanh' => '33'],
            ['ten_quan_huyen' => 'Huyện Khánh Vĩnh', 'id_tinh_thanh' => '33'],
            ['ten_quan_huyen' => 'Huyện Trường Sa', 'id_tinh_thanh' => '33'],
            ['ten_quan_huyen' => 'Huyện Vạn Ninh', 'id_tinh_thanh' => '33'],
            ['ten_quan_huyen' => 'Thành phố Rạch Giá (tỉnh lỵ)', 'id_tinh_thanh' => '34'],
            ['ten_quan_huyen' => 'Thành phố Hà Tiên', 'id_tinh_thanh' => '34'],
            ['ten_quan_huyen' => 'Thành phố Phú Quốc', 'id_tinh_thanh' => '34'],
            ['ten_quan_huyen' => 'Huyện An Biên', 'id_tinh_thanh' => '34'],
            ['ten_quan_huyen' => 'Huyện An Minh', 'id_tinh_thanh' => '34'],
            ['ten_quan_huyen' => 'Huyện Châu Thành', 'id_tinh_thanh' => '34'],
            ['ten_quan_huyen' => 'Huyện Giang Thành', 'id_tinh_thanh' => '34'],
            ['ten_quan_huyen' => 'Huyện Giồng Riềng', 'id_tinh_thanh' => '34'],
            ['ten_quan_huyen' => 'Huyện Gò Quao', 'id_tinh_thanh' => '34'],
            ['ten_quan_huyen' => 'Huyện Hòn Đất', 'id_tinh_thanh' => '34'],
            ['ten_quan_huyen' => 'Huyện Kiên Hải', 'id_tinh_thanh' => '34'],
            ['ten_quan_huyen' => 'Huyện Kiên Lương', 'id_tinh_thanh' => '34'],
            ['ten_quan_huyen' => 'Huyện Tân Hiệp', 'id_tinh_thanh' => '34'],
            ['ten_quan_huyen' => 'Huyện U Minh Thượng', 'id_tinh_thanh' => '34'],
            ['ten_quan_huyen' => 'Huyện Vĩnh Thuận', 'id_tinh_thanh' => '34'],
            ['ten_quan_huyen' => 'Thành phố Kon Tum (tỉnh lỵ)', 'id_tinh_thanh' => '35'],
            ['ten_quan_huyen' => 'Huyện Đăk Glei', 'id_tinh_thanh' => '35'],
            ['ten_quan_huyen' => 'Huyện Đăk Hà', 'id_tinh_thanh' => '35'],
            ['ten_quan_huyen' => 'Huyện Đăk Tô', 'id_tinh_thanh' => '35'],
            ['ten_quan_huyen' => 'Huyện Ia HxxDrai', 'id_tinh_thanh' => '35'],
            ['ten_quan_huyen' => 'Huyện Kon Plông', 'id_tinh_thanh' => '35'],
            ['ten_quan_huyen' => 'Huyện Kon Rẫy', 'id_tinh_thanh' => '35'],
            ['ten_quan_huyen' => 'Huyện Ngọc Hồi', 'id_tinh_thanh' => '35'],
            ['ten_quan_huyen' => 'Huyện Sa Thầy', 'id_tinh_thanh' => '35'],
            ['ten_quan_huyen' => 'Huyện Tu Mơ Rông', 'id_tinh_thanh' => '35'],
            ['ten_quan_huyen' => 'Thành phố Lai Châu (tỉnh lỵ)', 'id_tinh_thanh' => '36'],
            ['ten_quan_huyen' => 'Huyện Mường Tè', 'id_tinh_thanh' => '36'],
            ['ten_quan_huyen' => 'Huyện Nậm Nhùn', 'id_tinh_thanh' => '36'],
            ['ten_quan_huyen' => 'Huyện Phong Thổ', 'id_tinh_thanh' => '36'],
            ['ten_quan_huyen' => 'Huyện Sìn Hồ', 'id_tinh_thanh' => '36'],
            ['ten_quan_huyen' => 'Huyện Tam Đường', 'id_tinh_thanh' => '36'],
            ['ten_quan_huyen' => 'Huyện Tân Uyên', 'id_tinh_thanh' => '36'],
            ['ten_quan_huyen' => 'Huyện Than Uyên', 'id_tinh_thanh' => '36'],
            ['ten_quan_huyen' => 'Thành phố Đà Lạt (tỉnh lỵ)', 'id_tinh_thanh' => '37'],
            ['ten_quan_huyen' => 'Thành phố Bảo Lộc', 'id_tinh_thanh' => '37'],
            ['ten_quan_huyen' => 'Huyện Bảo Lâm', 'id_tinh_thanh' => '37'],
            ['ten_quan_huyen' => 'Huyện Cát Tiên', 'id_tinh_thanh' => '37'],
            ['ten_quan_huyen' => 'Huyện Đạ Huoai', 'id_tinh_thanh' => '37'],
            ['ten_quan_huyen' => 'Huyện Đạ Tẻh', 'id_tinh_thanh' => '37'],
            ['ten_quan_huyen' => 'Huyện Đam Rông', 'id_tinh_thanh' => '37'],
            ['ten_quan_huyen' => 'Huyện Di Linh', 'id_tinh_thanh' => '37'],
            ['ten_quan_huyen' => 'Huyện Đơn Dương', 'id_tinh_thanh' => '37'],
            ['ten_quan_huyen' => 'Huyện Đức Trọng', 'id_tinh_thanh' => '37'],
            ['ten_quan_huyen' => 'Huyện Lạc Dương', 'id_tinh_thanh' => '37'],
            ['ten_quan_huyen' => 'Huyện Lâm Hà', 'id_tinh_thanh' => '37'],
            ['ten_quan_huyen' => 'Thành phố Lạng Sơn (tỉnh lỵ)', 'id_tinh_thanh' => '38'],
            ['ten_quan_huyen' => 'Huyện Bắc Sơn', 'id_tinh_thanh' => '38'],
            ['ten_quan_huyen' => 'Huyện Bình Gia', 'id_tinh_thanh' => '38'],
            ['ten_quan_huyen' => 'Huyện Cao Lộc', 'id_tinh_thanh' => '38'],
            ['ten_quan_huyen' => 'Huyện Chi Lăng', 'id_tinh_thanh' => '38'],
            ['ten_quan_huyen' => 'Huyện Đình Lập', 'id_tinh_thanh' => '38'],
            ['ten_quan_huyen' => 'Huyện Hữu Lũng', 'id_tinh_thanh' => '38'],
            ['ten_quan_huyen' => 'Huyện Lộc Bình', 'id_tinh_thanh' => '38'],
            ['ten_quan_huyen' => 'Huyện Tràng Định', 'id_tinh_thanh' => '38'],
            ['ten_quan_huyen' => 'Huyện Văn Lãng', 'id_tinh_thanh' => '38'],
            ['ten_quan_huyen' => 'Huyện Văn Quan', 'id_tinh_thanh' => '38'],
            ['ten_quan_huyen' => 'Thành phố Lào Cai (tỉnh lỵ)', 'id_tinh_thanh' => '39'],
            ['ten_quan_huyen' => 'Thị xã Sa Pa', 'id_tinh_thanh' => '39'],
            ['ten_quan_huyen' => 'Huyện Bắc Hà', 'id_tinh_thanh' => '39'],
            ['ten_quan_huyen' => 'Huyện Bảo Thắng', 'id_tinh_thanh' => '39'],
            ['ten_quan_huyen' => 'Huyện Bảo Yên', 'id_tinh_thanh' => '39'],
            ['ten_quan_huyen' => 'Huyện Bát Xát', 'id_tinh_thanh' => '39'],
            ['ten_quan_huyen' => 'Huyện Mường Khương', 'id_tinh_thanh' => '39'],
            ['ten_quan_huyen' => 'Huyện Si Ma Cai', 'id_tinh_thanh' => '39'],
            ['ten_quan_huyen' => 'Huyện Văn Bàn', 'id_tinh_thanh' => '39'],
            ['ten_quan_huyen' => 'Thành phố Tân An (tỉnh lỵ)', 'id_tinh_thanh' => '40'],
            ['ten_quan_huyen' => 'Thị xã Kiến Tường', 'id_tinh_thanh' => '40'],
            ['ten_quan_huyen' => 'Huyện Bến Lức', 'id_tinh_thanh' => '40'],
            ['ten_quan_huyen' => 'Huyện Cần Đước', 'id_tinh_thanh' => '40'],
            ['ten_quan_huyen' => 'Huyện Cần Giuộc', 'id_tinh_thanh' => '40'],
            ['ten_quan_huyen' => 'Huyện Châu Thành', 'id_tinh_thanh' => '40'],
            ['ten_quan_huyen' => 'Huyện Đức Hòa', 'id_tinh_thanh' => '40'],
            ['ten_quan_huyen' => 'Huyện Đức Huệ', 'id_tinh_thanh' => '40'],
            ['ten_quan_huyen' => 'Huyện Mộc Hóa', 'id_tinh_thanh' => '40'],
            ['ten_quan_huyen' => 'Huyện Tân Hưng', 'id_tinh_thanh' => '40'],
            ['ten_quan_huyen' => 'Huyện Tân Thạnh', 'id_tinh_thanh' => '40'],
            ['ten_quan_huyen' => 'Huyện Tân Trụ', 'id_tinh_thanh' => '40'],
            ['ten_quan_huyen' => 'Huyện Thạnh Hóa', 'id_tinh_thanh' => '40'],
            ['ten_quan_huyen' => 'Huyện Thủ Thừa', 'id_tinh_thanh' => '40'],
            ['ten_quan_huyen' => 'Huyện Vĩnh Hưng', 'id_tinh_thanh' => '40'],
            ['ten_quan_huyen' => 'Thành phố Nam Định (tỉnh lỵ)', 'id_tinh_thanh' => '41'],
            ['ten_quan_huyen' => 'Huyện Giao Thủy', 'id_tinh_thanh' => '41'],
            ['ten_quan_huyen' => 'Huyện Hải Hậu', 'id_tinh_thanh' => '41'],
            ['ten_quan_huyen' => 'Huyện Mỹ Lộc', 'id_tinh_thanh' => '41'],
            ['ten_quan_huyen' => 'Huyện Nam Trực', 'id_tinh_thanh' => '41'],
            ['ten_quan_huyen' => 'Huyện Nghĩa Hưng', 'id_tinh_thanh' => '41'],
            ['ten_quan_huyen' => 'Huyện Trực Ninh', 'id_tinh_thanh' => '41'],
            ['ten_quan_huyen' => 'Huyện Vụ Bản', 'id_tinh_thanh' => '41'],
            ['ten_quan_huyen' => 'Huyện Xuân Trường', 'id_tinh_thanh' => '41'],
            ['ten_quan_huyen' => 'Huyện Ý Yên', 'id_tinh_thanh' => '41'],
            ['ten_quan_huyen' => 'Thành phố Vinh (tỉnh lỵ)', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Thị xã Cửa Lò', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Thị xã Hoàng Mai', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Thị xã Thái Hòa', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Huyện Anh Sơn', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Huyện Con Cuông', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Huyện Diễn Châu', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Huyện Đô Lương', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Huyện Hưng Nguyên', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Huyện Kỳ Sơn', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Huyện Nam Đàn', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Huyện Nghi Lộc', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Huyện Nghĩa Đàn', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Huyện Quế Phong', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Huyện Quỳ Châu', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Huyện Quỳ Hợp', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Huyện Quỳnh Lưu', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Huyện Tân Kỳ', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Huyện Thanh Chương', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Huyện Tương Dương', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Huyện Yên Thành', 'id_tinh_thanh' => '42'],
            ['ten_quan_huyen' => 'Thành phố Ninh Bình (tỉnh lỵ)', 'id_tinh_thanh' => '43'],
            ['ten_quan_huyen' => 'Thành phố Tam Điệp', 'id_tinh_thanh' => '43'],
            ['ten_quan_huyen' => 'Huyện Gia Viễn', 'id_tinh_thanh' => '43'],
            ['ten_quan_huyen' => 'Huyện Hoa Lư', 'id_tinh_thanh' => '43'],
            ['ten_quan_huyen' => 'Huyện Kim Sơn', 'id_tinh_thanh' => '43'],
            ['ten_quan_huyen' => 'Huyện Nho Quan', 'id_tinh_thanh' => '43'],
            ['ten_quan_huyen' => 'Huyện Yên Khánh', 'id_tinh_thanh' => '43'],
            ['ten_quan_huyen' => 'Huyện Yên Mô', 'id_tinh_thanh' => '43'],
            ['ten_quan_huyen' => 'Thành phố Phan Rang - Tháp Chàm (tỉnh lỵ)', 'id_tinh_thanh' => '44'],
            ['ten_quan_huyen' => 'Huyện Bác Ái', 'id_tinh_thanh' => '44'],
            ['ten_quan_huyen' => 'Huyện Ninh Hải', 'id_tinh_thanh' => '44'],
            ['ten_quan_huyen' => 'Huyện Ninh Phước', 'id_tinh_thanh' => '44'],
            ['ten_quan_huyen' => 'Huyện Ninh Sơn', 'id_tinh_thanh' => '44'],
            ['ten_quan_huyen' => 'Huyện Thuận Bắc', 'id_tinh_thanh' => '44'],
            ['ten_quan_huyen' => 'Huyện Thuận Nam', 'id_tinh_thanh' => '44'],
            ['ten_quan_huyen' => 'Thành phố Việt Trì (tỉnh lỵ)', 'id_tinh_thanh' => '45'],
            ['ten_quan_huyen' => 'Thị xã Phú Thọ', 'id_tinh_thanh' => '45'],
            ['ten_quan_huyen' => 'Huyện Cẩm Khê', 'id_tinh_thanh' => '45'],
            ['ten_quan_huyen' => 'Huyện Đoan Hùng', 'id_tinh_thanh' => '45'],
            ['ten_quan_huyen' => 'Huyện Hạ Hòa', 'id_tinh_thanh' => '45'],
            ['ten_quan_huyen' => 'Huyện Lâm Thao', 'id_tinh_thanh' => '45'],
            ['ten_quan_huyen' => 'Huyện Phù Ninh', 'id_tinh_thanh' => '45'],
            ['ten_quan_huyen' => 'Huyện Tam Nông', 'id_tinh_thanh' => '45'],
            ['ten_quan_huyen' => 'Huyện Tân Sơn', 'id_tinh_thanh' => '45'],
            ['ten_quan_huyen' => 'Huyện Thanh Ba', 'id_tinh_thanh' => '45'],
            ['ten_quan_huyen' => 'Huyện Thanh Sơn', 'id_tinh_thanh' => '45'],
            ['ten_quan_huyen' => 'Huyện Thanh Thủy', 'id_tinh_thanh' => '45'],
            ['ten_quan_huyen' => 'Huyện Yên Lập', 'id_tinh_thanh' => '45'],
            ['ten_quan_huyen' => 'Thành phố Tuy Hòa (tỉnh lỵ)', 'id_tinh_thanh' => '46'],
            ['ten_quan_huyen' => 'Thị xã Đông Hòa', 'id_tinh_thanh' => '46'],
            ['ten_quan_huyen' => 'Thị xã Sông Cầu', 'id_tinh_thanh' => '46'],
            ['ten_quan_huyen' => 'Huyện Đồng Xuân', 'id_tinh_thanh' => '46'],
            ['ten_quan_huyen' => 'Huyện Phú Hòa', 'id_tinh_thanh' => '46'],
            ['ten_quan_huyen' => 'Huyện Sơn Hòa', 'id_tinh_thanh' => '46'],
            ['ten_quan_huyen' => 'Huyện Sông Hinh', 'id_tinh_thanh' => '46'],
            ['ten_quan_huyen' => 'Huyện Tây Hòa', 'id_tinh_thanh' => '46'],
            ['ten_quan_huyen' => 'Huyện Tuy An', 'id_tinh_thanh' => '46'],
            ['ten_quan_huyen' => 'Thành phố Đồng Hới (tỉnh lỵ)', 'id_tinh_thanh' => '47'],
            ['ten_quan_huyen' => 'Thị xã Ba Đồn', 'id_tinh_thanh' => '47'],
            ['ten_quan_huyen' => 'Huyện Bố Trạch', 'id_tinh_thanh' => '47'],
            ['ten_quan_huyen' => 'Huyện Lệ Thủy', 'id_tinh_thanh' => '47'],
            ['ten_quan_huyen' => 'Huyện Minh Hóa', 'id_tinh_thanh' => '47'],
            ['ten_quan_huyen' => 'Huyện Quảng Ninh', 'id_tinh_thanh' => '47'],
            ['ten_quan_huyen' => 'Huyện Quảng Trạch', 'id_tinh_thanh' => '47'],
            ['ten_quan_huyen' => 'Huyện Tuyên Hóa', 'id_tinh_thanh' => '47'],
            ['ten_quan_huyen' => 'Thành phố Tam Kỳ (tỉnh lỵ)', 'id_tinh_thanh' => '48'],
            ['ten_quan_huyen' => 'Thành phố Hội An', 'id_tinh_thanh' => '48'],
            ['ten_quan_huyen' => 'Thị xã Điện Bàn', 'id_tinh_thanh' => '48'],
            ['ten_quan_huyen' => 'Huyện Bắc Trà My', 'id_tinh_thanh' => '48'],
            ['ten_quan_huyen' => 'Huyện Đại Lộc', 'id_tinh_thanh' => '48'],
            ['ten_quan_huyen' => 'Huyện Đông Giang', 'id_tinh_thanh' => '48'],
            ['ten_quan_huyen' => 'Huyện Duy Xuyên', 'id_tinh_thanh' => '48'],
            ['ten_quan_huyen' => 'Huyện Hiệp Đức', 'id_tinh_thanh' => '48'],
            ['ten_quan_huyen' => 'Huyện Nam Giang', 'id_tinh_thanh' => '48'],
            ['ten_quan_huyen' => 'Huyện Nam Trà My', 'id_tinh_thanh' => '48'],
            ['ten_quan_huyen' => 'Huyện Nông Sơn', 'id_tinh_thanh' => '48'],
            ['ten_quan_huyen' => 'Huyện Núi Thành', 'id_tinh_thanh' => '48'],
            ['ten_quan_huyen' => 'Huyện Phú Ninh', 'id_tinh_thanh' => '48'],
            ['ten_quan_huyen' => 'Huyện Phước Sơn', 'id_tinh_thanh' => '48'],
            ['ten_quan_huyen' => 'Huyện Quế Sơn', 'id_tinh_thanh' => '48'],
            ['ten_quan_huyen' => 'Huyện Tây Giang', 'id_tinh_thanh' => '48'],
            ['ten_quan_huyen' => 'Huyện Thăng Bình', 'id_tinh_thanh' => '48'],
            ['ten_quan_huyen' => 'Huyện Tiên Phước', 'id_tinh_thanh' => '48'],
            ['ten_quan_huyen' => 'Thành phố Quảng Ngãi (tỉnh lỵ)', 'id_tinh_thanh' => '49'],
            ['ten_quan_huyen' => 'Thị xã Đức Phổ', 'id_tinh_thanh' => '49'],
            ['ten_quan_huyen' => 'Huyện Ba Tơ', 'id_tinh_thanh' => '49'],
            ['ten_quan_huyen' => 'Huyện Bình Sơn', 'id_tinh_thanh' => '49'],
            ['ten_quan_huyen' => 'Huyện Lý Sơn', 'id_tinh_thanh' => '49'],
            ['ten_quan_huyen' => 'Huyện Minh Long', 'id_tinh_thanh' => '49'],
            ['ten_quan_huyen' => 'Huyện Mộ Đức', 'id_tinh_thanh' => '49'],
            ['ten_quan_huyen' => 'Huyện Nghĩa Hành', 'id_tinh_thanh' => '49'],
            ['ten_quan_huyen' => 'Huyện Sơn Hà', 'id_tinh_thanh' => '49'],
            ['ten_quan_huyen' => 'Huyện Sơn Tây', 'id_tinh_thanh' => '49'],
            ['ten_quan_huyen' => 'Huyện Sơn Tịnh', 'id_tinh_thanh' => '49'],
            ['ten_quan_huyen' => 'Huyện Trà Bồng', 'id_tinh_thanh' => '49'],
            ['ten_quan_huyen' => 'Huyện Tư Nghĩa', 'id_tinh_thanh' => '49'],
            ['ten_quan_huyen' => 'Thành phố Hạ Long (tỉnh lỵ)', 'id_tinh_thanh' => '50'],
            ['ten_quan_huyen' => 'Thành phố Cẩm Phả', 'id_tinh_thanh' => '50'],
            ['ten_quan_huyen' => 'Thành phố Móng Cái', 'id_tinh_thanh' => '50'],
            ['ten_quan_huyen' => 'Thành phố Uông Bí', 'id_tinh_thanh' => '50'],
            ['ten_quan_huyen' => 'Thị xã Đông Triều', 'id_tinh_thanh' => '50'],
            ['ten_quan_huyen' => 'Thị xã Quảng Yên', 'id_tinh_thanh' => '50'],
            ['ten_quan_huyen' => 'Huyện Ba Chẽ', 'id_tinh_thanh' => '50'],
            ['ten_quan_huyen' => 'Huyện Bình Liêu', 'id_tinh_thanh' => '50'],
            ['ten_quan_huyen' => 'Huyện Cô Tô', 'id_tinh_thanh' => '50'],
            ['ten_quan_huyen' => 'Huyện Đầm Hà', 'id_tinh_thanh' => '50'],
            ['ten_quan_huyen' => 'Huyện Hải Hà', 'id_tinh_thanh' => '50'],
            ['ten_quan_huyen' => 'Huyện Tiên Yên', 'id_tinh_thanh' => '50'],
            ['ten_quan_huyen' => 'Huyện Vân Đồn', 'id_tinh_thanh' => '50'],
            ['ten_quan_huyen' => 'Thành phố Đông Hà (tỉnh lỵ)', 'id_tinh_thanh' => '51'],
            ['ten_quan_huyen' => 'Thị xã Quảng Trị', 'id_tinh_thanh' => '51'],
            ['ten_quan_huyen' => 'Huyện Cam Lộ', 'id_tinh_thanh' => '51'],
            ['ten_quan_huyen' => 'Huyện Cồn Cỏ', 'id_tinh_thanh' => '51'],
            ['ten_quan_huyen' => 'Huyện Đakrông', 'id_tinh_thanh' => '51'],
            ['ten_quan_huyen' => 'Huyện Gio Linh', 'id_tinh_thanh' => '51'],
            ['ten_quan_huyen' => 'Huyện Hải Lăng', 'id_tinh_thanh' => '51'],
            ['ten_quan_huyen' => 'Huyện Hướng Hóa', 'id_tinh_thanh' => '51'],
            ['ten_quan_huyen' => 'Huyện Triệu Phong', 'id_tinh_thanh' => '51'],
            ['ten_quan_huyen' => 'Huyện Vĩnh Linh', 'id_tinh_thanh' => '51'],
            ['ten_quan_huyen' => 'Thành phố Sóc Trăng (tỉnh lỵ)', 'id_tinh_thanh' => '52'],
            ['ten_quan_huyen' => 'Thị xã Ngã Năm', 'id_tinh_thanh' => '52'],
            ['ten_quan_huyen' => 'Thị xã Vĩnh Châu', 'id_tinh_thanh' => '52'],
            ['ten_quan_huyen' => 'Huyện Châu Thành', 'id_tinh_thanh' => '52'],
            ['ten_quan_huyen' => 'Huyện Cù Lao Dung', 'id_tinh_thanh' => '52'],
            ['ten_quan_huyen' => 'Huyện Kế Sách', 'id_tinh_thanh' => '52'],
            ['ten_quan_huyen' => 'Huyện Long Phú', 'id_tinh_thanh' => '52'],
            ['ten_quan_huyen' => 'Huyện Mỹ Tú', 'id_tinh_thanh' => '52'],
            ['ten_quan_huyen' => 'Huyện Mỹ Xuyên', 'id_tinh_thanh' => '52'],
            ['ten_quan_huyen' => 'Huyện Thạnh Trị', 'id_tinh_thanh' => '52'],
            ['ten_quan_huyen' => 'Huyện Trần Đề', 'id_tinh_thanh' => '52'],
            ['ten_quan_huyen' => 'Thành phố Sơn La (tỉnh lỵ)', 'id_tinh_thanh' => '53'],
            ['ten_quan_huyen' => 'Huyện Bắc Yên', 'id_tinh_thanh' => '53'],
            ['ten_quan_huyen' => 'Huyện Mai Sơn', 'id_tinh_thanh' => '53'],
            ['ten_quan_huyen' => 'Huyện Mộc Châu', 'id_tinh_thanh' => '53'],
            ['ten_quan_huyen' => 'Huyện Mường La', 'id_tinh_thanh' => '53'],
            ['ten_quan_huyen' => 'Huyện Phù Yên', 'id_tinh_thanh' => '53'],
            ['ten_quan_huyen' => 'Huyện Quỳnh Nhai', 'id_tinh_thanh' => '53'],
            ['ten_quan_huyen' => 'Huyện Sông Mã', 'id_tinh_thanh' => '53'],
            ['ten_quan_huyen' => 'Huyện Sốp Cộp', 'id_tinh_thanh' => '53'],
            ['ten_quan_huyen' => 'Huyện Thuận Châu', 'id_tinh_thanh' => '53'],
            ['ten_quan_huyen' => 'Huyện Vân Hồ', 'id_tinh_thanh' => '53'],
            ['ten_quan_huyen' => 'Huyện Yên Châu', 'id_tinh_thanh' => '53'],
            ['ten_quan_huyen' => 'Thành phố Tây Ninh (tỉnh lỵ)', 'id_tinh_thanh' => '54'],
            ['ten_quan_huyen' => 'Thị xã Hòa Thành', 'id_tinh_thanh' => '54'],
            ['ten_quan_huyen' => 'Thị xã Trảng Bàng', 'id_tinh_thanh' => '54'],
            ['ten_quan_huyen' => 'Huyện Bến Cầu', 'id_tinh_thanh' => '54'],
            ['ten_quan_huyen' => 'Huyện Châu Thành', 'id_tinh_thanh' => '54'],
            ['ten_quan_huyen' => 'Huyện Dương Minh Châu', 'id_tinh_thanh' => '54'],
            ['ten_quan_huyen' => 'Huyện Gò Dầu', 'id_tinh_thanh' => '54'],
            ['ten_quan_huyen' => 'Huyện Tân Biên', 'id_tinh_thanh' => '54'],
            ['ten_quan_huyen' => 'Huyện Tân Châu', 'id_tinh_thanh' => '54'],
            ['ten_quan_huyen' => 'Thành phố Thái Bình (tỉnh lỵ)', 'id_tinh_thanh' => '55'],
            ['ten_quan_huyen' => 'Huyện Đông Hưng', 'id_tinh_thanh' => '55'],
            ['ten_quan_huyen' => 'Huyện Hưng Hà', 'id_tinh_thanh' => '55'],
            ['ten_quan_huyen' => 'Huyện Kiến Xương', 'id_tinh_thanh' => '55'],
            ['ten_quan_huyen' => 'Huyện Quỳnh Phụ', 'id_tinh_thanh' => '55'],
            ['ten_quan_huyen' => 'Huyện Thái Thụy', 'id_tinh_thanh' => '55'],
            ['ten_quan_huyen' => 'Huyện Tiền Hải', 'id_tinh_thanh' => '55'],
            ['ten_quan_huyen' => 'Huyện Vũ Thư', 'id_tinh_thanh' => '55'],
            ['ten_quan_huyen' => 'Thành phố Thái Nguyên (tỉnh lỵ)', 'id_tinh_thanh' => '56'],
            ['ten_quan_huyen' => 'Thành phố Sông Công', 'id_tinh_thanh' => '56'],
            ['ten_quan_huyen' => 'Thị xã Phổ Yên', 'id_tinh_thanh' => '56'],
            ['ten_quan_huyen' => 'Huyện Đại Từ', 'id_tinh_thanh' => '56'],
            ['ten_quan_huyen' => 'Huyện Định Hóa', 'id_tinh_thanh' => '56'],
            ['ten_quan_huyen' => 'Huyện Đồng Hỷ', 'id_tinh_thanh' => '56'],
            ['ten_quan_huyen' => 'Huyện Phú Bình', 'id_tinh_thanh' => '56'],
            ['ten_quan_huyen' => 'Huyện Phú Lương', 'id_tinh_thanh' => '56'],
            ['ten_quan_huyen' => 'Huyện Võ Nhai', 'id_tinh_thanh' => '56'],
            ['ten_quan_huyen' => 'Thành phố Thanh Hóa (tỉnh lỵ)', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Thành phố Sầm Sơn', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Thị xã Bỉm Sơn', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Thị xã Nghi Sơn', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Bá Thước', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Cẩm Thủy', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Đông Sơn', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Hà Trung', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Hậu Lộc', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Hoằng Hóa', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Lang Chánh', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Mường Lát', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Nga Sơn', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Ngọc Lặc', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Như Thanh', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Như Xuân', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Nông Cống', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Quan Hóa', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Quan Sơn', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Quảng Xương', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Thạch Thành', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Thiệu Hóa', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Thọ Xuân', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Thường Xuân', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Triệu Sơn', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Vĩnh Lộc', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Huyện Yên Định', 'id_tinh_thanh' => '57'],
            ['ten_quan_huyen' => 'Thành phố Huế (tỉnh lỵ)', 'id_tinh_thanh' => '58'],
            ['ten_quan_huyen' => 'Thị xã Hương Thủy', 'id_tinh_thanh' => '58'],
            ['ten_quan_huyen' => 'Thị xã Hương Trà', 'id_tinh_thanh' => '58'],
            ['ten_quan_huyen' => 'Huyện A Lưới', 'id_tinh_thanh' => '58'],
            ['ten_quan_huyen' => 'Huyện Nam Đông', 'id_tinh_thanh' => '58'],
            ['ten_quan_huyen' => 'Huyện Phong Điền', 'id_tinh_thanh' => '58'],
            ['ten_quan_huyen' => 'Huyện Phú Lộc', 'id_tinh_thanh' => '58'],
            ['ten_quan_huyen' => 'Huyện Phú Vang', 'id_tinh_thanh' => '58'],
            ['ten_quan_huyen' => 'Huyện Quảng Điền', 'id_tinh_thanh' => '58'],
            ['ten_quan_huyen' => 'Thành phố Mỹ Tho (tỉnh lỵ)', 'id_tinh_thanh' => '59'],
            ['ten_quan_huyen' => 'Thị xã Cai Lậy', 'id_tinh_thanh' => '59'],
            ['ten_quan_huyen' => 'Thị xã Gò Công', 'id_tinh_thanh' => '59'],
            ['ten_quan_huyen' => 'Huyện Cái Bè', 'id_tinh_thanh' => '59'],
            ['ten_quan_huyen' => 'Huyện Cai Lậy', 'id_tinh_thanh' => '59'],
            ['ten_quan_huyen' => 'Huyện Châu Thành', 'id_tinh_thanh' => '59'],
            ['ten_quan_huyen' => 'Huyện Chợ Gạo', 'id_tinh_thanh' => '59'],
            ['ten_quan_huyen' => 'Huyện Gò Công Đông', 'id_tinh_thanh' => '59'],
            ['ten_quan_huyen' => 'Huyện Gò Công Tây', 'id_tinh_thanh' => '59'],
            ['ten_quan_huyen' => 'Huyện Tân Phú Đông', 'id_tinh_thanh' => '59'],
            ['ten_quan_huyen' => 'Huyện Tân Phước', 'id_tinh_thanh' => '59'],
            ['ten_quan_huyen' => 'Thành phố Trà Vinh (tỉnh lỵ)', 'id_tinh_thanh' => '60'],
            ['ten_quan_huyen' => 'Thị xã Duyên Hải', 'id_tinh_thanh' => '60'],
            ['ten_quan_huyen' => 'Huyện Càng Long', 'id_tinh_thanh' => '60'],
            ['ten_quan_huyen' => 'Huyện Cầu Kè', 'id_tinh_thanh' => '60'],
            ['ten_quan_huyen' => 'Huyện Cầu Ngang', 'id_tinh_thanh' => '60'],
            ['ten_quan_huyen' => 'Huyện Châu Thành', 'id_tinh_thanh' => '60'],
            ['ten_quan_huyen' => 'Huyện Duyên Hải', 'id_tinh_thanh' => '60'],
            ['ten_quan_huyen' => 'Huyện Tiểu Cần', 'id_tinh_thanh' => '60'],
            ['ten_quan_huyen' => 'Huyện Trà Cú', 'id_tinh_thanh' => '60'],
            ['ten_quan_huyen' => 'Thành phố Tuyên Quang (tỉnh lỵ)', 'id_tinh_thanh' => '61'],
            ['ten_quan_huyen' => 'Huyện Chiêm Hóa', 'id_tinh_thanh' => '61'],
            ['ten_quan_huyen' => 'Huyện Hàm Yên', 'id_tinh_thanh' => '61'],
            ['ten_quan_huyen' => 'Huyện Lâm Bình', 'id_tinh_thanh' => '61'],
            ['ten_quan_huyen' => 'Huyện Na Hang', 'id_tinh_thanh' => '61'],
            ['ten_quan_huyen' => 'Huyện Sơn Dương', 'id_tinh_thanh' => '61'],
            ['ten_quan_huyen' => 'Huyện Yên Sơn', 'id_tinh_thanh' => '61'],
            ['ten_quan_huyen' => 'Thành phố Vĩnh Long (tỉnh lỵ)', 'id_tinh_thanh' => '62'],
            ['ten_quan_huyen' => 'Thị xã Bình Minh', 'id_tinh_thanh' => '62'],
            ['ten_quan_huyen' => 'Huyện Bình Tân', 'id_tinh_thanh' => '62'],
            ['ten_quan_huyen' => 'Huyện Long Hồ', 'id_tinh_thanh' => '62'],
            ['ten_quan_huyen' => 'Huyện Mang Thít', 'id_tinh_thanh' => '62'],
            ['ten_quan_huyen' => 'Huyện Tam Bình', 'id_tinh_thanh' => '62'],
            ['ten_quan_huyen' => 'Huyện Trà Ôn', 'id_tinh_thanh' => '62'],
            ['ten_quan_huyen' => 'Huyện Vũng Liêm', 'id_tinh_thanh' => '62'],
            ['ten_quan_huyen' => 'Thành phố Vĩnh Yên (tỉnh lỵ)', 'id_tinh_thanh' => '63'],
            ['ten_quan_huyen' => 'Thành phố Phúc Yên', 'id_tinh_thanh' => '63'],
            ['ten_quan_huyen' => 'Huyện Bình Xuyên', 'id_tinh_thanh' => '63'],
            ['ten_quan_huyen' => 'Huyện Lập Thạch', 'id_tinh_thanh' => '63'],
            ['ten_quan_huyen' => 'Huyện Sông Lô', 'id_tinh_thanh' => '63'],
            ['ten_quan_huyen' => 'Huyện Tam Đảo', 'id_tinh_thanh' => '63'],
            ['ten_quan_huyen' => 'Huyện Tam Dương', 'id_tinh_thanh' => '63'],
            ['ten_quan_huyen' => 'Huyện Vĩnh Tường', 'id_tinh_thanh' => '63'],
            ['ten_quan_huyen' => 'Huyện Yên Lạc', 'id_tinh_thanh' => '63'],
            ['ten_quan_huyen' => 'Thành phố Yên Bái (tỉnh lỵ)', 'id_tinh_thanh' => '64'],
            ['ten_quan_huyen' => 'Thị xã Nghĩa Lộ', 'id_tinh_thanh' => '64'],
            ['ten_quan_huyen' => 'Huyện Lục Yên', 'id_tinh_thanh' => '64'],
            ['ten_quan_huyen' => 'Huyện Mù Cang Chải', 'id_tinh_thanh' => '64'],
            ['ten_quan_huyen' => 'Huyện Trạm Tấu', 'id_tinh_thanh' => '64'],
            ['ten_quan_huyen' => 'Huyện Trấn Yên', 'id_tinh_thanh' => '64'],
            ['ten_quan_huyen' => 'Huyện Văn Chấn', 'id_tinh_thanh' => '64'],
            ['ten_quan_huyen' => 'Huyện Văn Yên', 'id_tinh_thanh' => '64'],
            ['ten_quan_huyen' => 'Huyện Yên Bình', 'id_tinh_thanh' => '64'],
        ]);

    }
}
